package com.qw.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("cms_article", "id", CmsArticle.class);
		arp.addMapping("cms_article_cat", "id", CmsArticleCat.class);
		arp.addMapping("oms_config", "id", Config.class);
		arp.addMapping("oms_operate", "id", Operate.class);
		arp.addMapping("oms_region", "id", Region.class);
		arp.addMapping("oms_role", "id", Role.class);
		// Composite Primary Key order: operateId,roleId
		arp.addMapping("oms_role_operation", "operateId,roleId", RoleOperation.class);
		arp.addMapping("oms_staff", "id", Staff.class);
		// Composite Primary Key order: adminId,roleId
		arp.addMapping("oms_staff_role", "adminId,roleId", StaffRole.class);
	}
}

