package com.qw.model;

import com.qw.model.base.BaseArticleCat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleCat extends BaseArticleCat<ArticleCat> {
	public static final ArticleCat dao = new ArticleCat().dao();
}
