package com.qw.model;

import com.qw.model.base.BaseBrand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Brand extends BaseBrand<Brand> {
	public static final Brand dao = new Brand().dao();
}
