package com.qw.model;

import com.qw.model.base.BaseCart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cart extends BaseCart<Cart> {
	public static final Cart dao = new Cart().dao();
}
