package com.qw.model;

import com.qw.model.base.BaseCmsArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmsArticle extends BaseCmsArticle<CmsArticle> {
	public static final CmsArticle dao = new CmsArticle().dao();
}
