package com.qw.model;

import com.qw.model.base.BaseCmsArticleCat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmsArticleCat extends BaseCmsArticleCat<CmsArticleCat> {
	public static final CmsArticleCat dao = new CmsArticleCat().dao();
}
