package com.qw.model;

import com.qw.model.base.BaseCouponPosition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CouponPosition extends BaseCouponPosition<CouponPosition> {
	public static final CouponPosition dao = new CouponPosition().dao();
}
