package com.qw.model;

import com.qw.model.base.BaseCouponBusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CouponBusiness extends BaseCouponBusiness<CouponBusiness> {
	public static final CouponBusiness dao = new CouponBusiness().dao();
}
