package com.qw.model;

import com.qw.model.base.BaseCouponActivity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CouponActivity extends BaseCouponActivity<CouponActivity> {
	public static final CouponActivity dao = new CouponActivity().dao();
}
