package com.qw.model;

import com.qw.model.base.BaseCouponLadder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CouponLadder extends BaseCouponLadder<CouponLadder> {
	public static final CouponLadder dao = new CouponLadder().dao();
}
