package com.qw.model;

import com.qw.model.base.BaseCouponList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CouponList extends BaseCouponList<CouponList> {
	public static final CouponList dao = new CouponList().dao();
}
