package com.qw.model;

import com.qw.model.base.BaseCouponOrderRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CouponOrderRecord extends BaseCouponOrderRecord<CouponOrderRecord> {
	public static final CouponOrderRecord dao = new CouponOrderRecord().dao();
}
