package com.qw.model;

import com.qw.model.base.BaseCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Coupon extends BaseCoupon<Coupon> {
	public static final Coupon dao = new Coupon().dao();
}
