package com.qw.model;

import com.qw.model.base.BaseDeliveryDoc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeliveryDoc extends BaseDeliveryDoc<DeliveryDoc> {
	public static final DeliveryDoc dao = new DeliveryDoc().dao();
}
