package com.qw.model;

import com.qw.model.base.BaseDoorServer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DoorServer extends BaseDoorServer<DoorServer> {
	public static final DoorServer dao = new DoorServer().dao();
}
