package com.qw.model;

import com.qw.model.base.BaseExpressCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExpressCompany extends BaseExpressCompany<ExpressCompany> {
	public static final ExpressCompany dao = new ExpressCompany().dao();
}
