package com.qw.model;

import com.qw.model.base.BaseFlashSale;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlashSale extends BaseFlashSale<FlashSale> {
	public static final FlashSale dao = new FlashSale().dao();
}
