package com.qw.model;

import com.qw.model.base.BaseFlashInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlashInfo extends BaseFlashInfo<FlashInfo> {
	public static final FlashInfo dao = new FlashInfo().dao();
}
