package com.qw.model;

import com.qw.model.base.BaseFreightRegion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FreightRegion extends BaseFreightRegion<FreightRegion> {
	public static final FreightRegion dao = new FreightRegion().dao();
}
