package com.qw.model;

import com.qw.model.base.BaseFreightConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FreightConfig extends BaseFreightConfig<FreightConfig> {
	public static final FreightConfig dao = new FreightConfig().dao();
}
