package com.qw.model;

import com.qw.model.base.BaseFreightTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FreightTemplate extends BaseFreightTemplate<FreightTemplate> {
	public static final FreightTemplate dao = new FreightTemplate().dao();
}
