package com.qw.model;

import com.qw.model.base.BaseGood;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Good extends BaseGood<Good> {
	public static final Good dao = new Good().dao();
}
