package com.qw.model;

import com.qw.model.base.BaseGoodImages;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodImages extends BaseGoodImages<GoodImages> {
	public static final GoodImages dao = new GoodImages().dao();
}
