package com.qw.model;

import com.qw.model.base.BaseGoodCollect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodCollect extends BaseGoodCollect<GoodCollect> {
	public static final GoodCollect dao = new GoodCollect().dao();
}
