package com.qw.model;

import com.qw.model.base.BaseGoodSku;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodSku extends BaseGoodSku<GoodSku> {
	public static final GoodSku dao = new GoodSku().dao();
}
