package com.qw.model;

import com.qw.model.base.BaseGoodVisit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodVisit extends BaseGoodVisit<GoodVisit> {
	public static final GoodVisit dao = new GoodVisit().dao();
}
