package com.qw.model;

import com.qw.model.base.BaseGoodCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodCategory extends BaseGoodCategory<GoodCategory> {
	public static final GoodCategory dao = new GoodCategory().dao();
}
