package com.qw.model;

import com.qw.model.base.BaseHomeSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HomeSet extends BaseHomeSet<HomeSet> {
	public static final HomeSet dao = new HomeSet().dao();
}
