package com.qw.model;

import com.qw.model.base.BaseLotteryGood;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LotteryGood extends BaseLotteryGood<LotteryGood> {
	public static final LotteryGood dao = new LotteryGood().dao();
}
