package com.qw.model;

import com.qw.model.base.BaseLotteryOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LotteryOrder extends BaseLotteryOrder<LotteryOrder> {
	public static final LotteryOrder dao = new LotteryOrder().dao();
}
