package com.qw.model;

import com.qw.model.base.BaseOperate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Operate extends BaseOperate<Operate> {
	public static final Operate dao = new Operate().dao();
}
