package com.qw.model;

import com.qw.model.base.BaseOrderComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderComment extends BaseOrderComment<OrderComment> {
	public static final OrderComment dao = new OrderComment().dao();
}
