package com.qw.model;

import com.qw.model.base.BaseOrderGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderGoods extends BaseOrderGoods<OrderGoods> {
	public static final OrderGoods dao = new OrderGoods().dao();
}
