package com.qw.model;

import com.qw.model.base.BaseOrderDivRate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderDivRate extends BaseOrderDivRate<OrderDivRate> {
	public static final OrderDivRate dao = new OrderDivRate().dao();
}
