package com.qw.model;

import com.qw.model.base.BasePointInvest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PointInvest extends BasePointInvest<PointInvest> {
	public static final PointInvest dao = new PointInvest().dao();
}
