package com.qw.model;

import com.qw.model.base.BasePointEffective;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PointEffective extends BasePointEffective<PointEffective> {
	public static final PointEffective dao = new PointEffective().dao();
}
