package com.qw.model;

import com.qw.model.base.BasePointWithdraw;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PointWithdraw extends BasePointWithdraw<PointWithdraw> {
	public static final PointWithdraw dao = new PointWithdraw().dao();
}
