package com.qw.model;

import com.qw.model.base.BasePointFreeze;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PointFreeze extends BasePointFreeze<PointFreeze> {
	public static final PointFreeze dao = new PointFreeze().dao();
}
