package com.qw.model;

import com.qw.model.base.BasePointSum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PointSum extends BasePointSum<PointSum> {
	public static final PointSum dao = new PointSum().dao();
}
