package com.qw.model;

import com.qw.model.base.BasePromOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromOrder extends BasePromOrder<PromOrder> {
	public static final PromOrder dao = new PromOrder().dao();
}
