package com.qw.model;

import com.qw.model.base.BasePromGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromGoods extends BasePromGoods<PromGoods> {
	public static final PromGoods dao = new PromGoods().dao();
}
