package com.qw.model;

import com.qw.model.base.BaseRecharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recharge extends BaseRecharge<Recharge> {
	public static final Recharge dao = new Recharge().dao();
}
