package com.qw.model;

import com.qw.model.base.BaseReturnGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReturnGoods extends BaseReturnGoods<ReturnGoods> {
	public static final ReturnGoods dao = new ReturnGoods().dao();
}
