package com.qw.model;

import com.qw.model.base.BaseRoleOperation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleOperation extends BaseRoleOperation<RoleOperation> {
	public static final RoleOperation dao = new RoleOperation().dao();
}
