package com.qw.model;

import com.qw.model.base.BaseSearchWord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SearchWord extends BaseSearchWord<SearchWord> {
	public static final SearchWord dao = new SearchWord().dao();
}
