package com.qw.model;

import com.qw.model.base.BaseServiceWorker;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ServiceWorker extends BaseServiceWorker<ServiceWorker> {
	public static final ServiceWorker dao = new ServiceWorker().dao();
}
