package com.qw.model;

import com.qw.model.base.BaseShippingArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShippingArea extends BaseShippingArea<ShippingArea> {
	public static final ShippingArea dao = new ShippingArea().dao();
}
