package com.qw.model;

import com.qw.model.base.BaseSmsLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsLog extends BaseSmsLog<SmsLog> {
	public static final SmsLog dao = new SmsLog().dao();
}
