package com.qw.model;

import com.qw.model.base.BaseSmsTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsTemplate extends BaseSmsTemplate<SmsTemplate> {
	public static final SmsTemplate dao = new SmsTemplate().dao();
}
