package com.qw.model;

import com.qw.model.base.BaseSpecItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpecItem extends BaseSpecItem<SpecItem> {
	public static final SpecItem dao = new SpecItem().dao();
}
