package com.qw.model;

import com.qw.model.base.BaseSpec;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Spec extends BaseSpec<Spec> {
	public static final Spec dao = new Spec().dao();
}
