package com.qw.model;

import com.qw.model.base.BaseStaffRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StaffRole extends BaseStaffRole<StaffRole> {
	public static final StaffRole dao = new StaffRole().dao();
}
