package com.qw.model;

import com.qw.model.base.BaseStaff;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Staff extends BaseStaff<Staff> {
	public static final Staff dao = new Staff().dao();
}
