package com.qw.model;

import com.qw.model.base.BaseStockLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StockLog extends BaseStockLog<StockLog> {
	public static final StockLog dao = new StockLog().dao();
}
