package com.qw.model;

import com.qw.model.base.BaseStoreApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreApply extends BaseStoreApply<StoreApply> {
	public static final StoreApply dao = new StoreApply().dao();
}
