package com.qw.model;

import com.qw.model.base.BaseStoreGoodsClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreGoodsClass extends BaseStoreGoodsClass<StoreGoodsClass> {
	public static final StoreGoodsClass dao = new StoreGoodsClass().dao();
}
