package com.qw.model;

import com.qw.model.base.BaseStoreAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreAddress extends BaseStoreAddress<StoreAddress> {
	public static final StoreAddress dao = new StoreAddress().dao();
}
