package com.qw.model;

import com.qw.model.base.BaseStoreLevel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreLevel extends BaseStoreLevel<StoreLevel> {
	public static final StoreLevel dao = new StoreLevel().dao();
}
