package com.qw.model;

import com.qw.model.base.BaseStoreLevelCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreLevelCategory extends BaseStoreLevelCategory<StoreLevelCategory> {
	public static final StoreLevelCategory dao = new StoreLevelCategory().dao();
}
