package com.qw.model;

import com.qw.model.base.BaseStoreLevelSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreLevelSet extends BaseStoreLevelSet<StoreLevelSet> {
	public static final StoreLevelSet dao = new StoreLevelSet().dao();
}
