package com.qw.model;

import com.qw.model.base.BaseStoreCollect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreCollect extends BaseStoreCollect<StoreCollect> {
	public static final StoreCollect dao = new StoreCollect().dao();
}
