package com.qw.model;

import com.qw.model.base.BaseUserBalance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserBalance extends BaseUserBalance<UserBalance> {
	public static final UserBalance dao = new UserBalance().dao();
}
