package com.qw.model;

import com.qw.model.base.BaseUserLevel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLevel extends BaseUserLevel<UserLevel> {
	public static final UserLevel dao = new UserLevel().dao();
}
