package com.qw.model;

import com.qw.model.base.BaseUserMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMessage extends BaseUserMessage<UserMessage> {
	public static final UserMessage dao = new UserMessage().dao();
}
