package com.qw.model;

import com.qw.model.base.BaseUserSign;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserSign extends BaseUserSign<UserSign> {
	public static final UserSign dao = new UserSign().dao();
}
