package com.qw.model;

import com.qw.model.base.BaseUserMsgTpl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMsgTpl extends BaseUserMsgTpl<UserMsgTpl> {
	public static final UserMsgTpl dao = new UserMsgTpl().dao();
}
