package com.qw.model;

import com.qw.model.base.BaseUserBalanceDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserBalanceDetail extends BaseUserBalanceDetail<UserBalanceDetail> {
	public static final UserBalanceDetail dao = new UserBalanceDetail().dao();
}
