package com.qw.model;

import com.qw.model.base.BaseWxbank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Wxbank extends BaseWxbank<Wxbank> {
	public static final Wxbank dao = new Wxbank().dao();
}
