package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePointWithdraw<M extends BasePointWithdraw<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 提现编号
	 */
	public void setWithdrawSn(java.lang.String withdrawSn) {
		set("withdraw_sn", withdrawSn);
	}

	/**
	 * 提现编号
	 */
	public java.lang.String getWithdrawSn() {
		return getStr("withdraw_sn");
	}

	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	/**
	 * 用户ID
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 提现状态（1待审核 2待打款 3已完成 5审核拒绝
	 */
	public void setWithdrawStatus(java.lang.Integer withdrawStatus) {
		set("withdraw_status", withdrawStatus);
	}

	/**
	 * 提现状态（1待审核 2待打款 3已完成 5审核拒绝
	 */
	public java.lang.Integer getWithdrawStatus() {
		return getInt("withdraw_status");
	}

	/**
	 * 积分值
	 */
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	/**
	 * 积分值
	 */
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	/**
	 * 扣除手续费以后的实际金额
	 */
	public void setActualAmount(java.math.BigDecimal actualAmount) {
		set("actual_amount", actualAmount);
	}

	/**
	 * 扣除手续费以后的实际金额
	 */
	public java.math.BigDecimal getActualAmount() {
		return get("actual_amount");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 开户行
	 */
	public void setBankName(java.lang.String bankName) {
		set("bankName", bankName);
	}

	/**
	 * 开户行
	 */
	public java.lang.String getBankName() {
		return getStr("bankName");
	}

	/**
	 * 银行卡号
	 */
	public void setBankCard(java.lang.String bankCard) {
		set("bankCard", bankCard);
	}

	/**
	 * 银行卡号
	 */
	public java.lang.String getBankCard() {
		return getStr("bankCard");
	}

	/**
	 * 审核人ID
	 */
	public void setAuthUserId(java.lang.Integer authUserId) {
		set("auth_user_id", authUserId);
	}

	/**
	 * 审核人ID
	 */
	public java.lang.Integer getAuthUserId() {
		return getInt("auth_user_id");
	}

	/**
	 * 审核时间
	 */
	public void setAuthTime(java.util.Date authTime) {
		set("auth_time", authTime);
	}

	/**
	 * 审核时间
	 */
	public java.util.Date getAuthTime() {
		return get("auth_time");
	}

	/**
	 * 支付人ID
	 */
	public void setPayUserId(java.lang.Integer payUserId) {
		set("pay_user_id", payUserId);
	}

	/**
	 * 支付人ID
	 */
	public java.lang.Integer getPayUserId() {
		return getInt("pay_user_id");
	}

	/**
	 * 支付时间
	 */
	public void setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
	}

	/**
	 * 支付时间
	 */
	public java.util.Date getPayTime() {
		return get("pay_time");
	}

	/**
	 * 支付编号（第三方支付回调后的单号，方便查询）
	 */
	public void setPaySn(java.lang.String paySn) {
		set("pay_sn", paySn);
	}

	/**
	 * 支付编号（第三方支付回调后的单号，方便查询）
	 */
	public java.lang.String getPaySn() {
		return getStr("pay_sn");
	}

	/**
	 * 支付方式（1人工打款 2微信红包 3微信零钱 4微信转银行卡 5支付宝余额 6支付宝转银行卡）
	 */
	public void setPayType(java.lang.Integer payType) {
		set("pay_type", payType);
	}

	/**
	 * 支付方式（1人工打款 2微信红包 3微信零钱 4微信转银行卡 5支付宝余额 6支付宝转银行卡）
	 */
	public java.lang.Integer getPayType() {
		return getInt("pay_type");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreatedBy(java.lang.String createdBy) {
		set("created_by", createdBy);
	}

	public java.lang.String getCreatedBy() {
		return getStr("created_by");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

}
