package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShippingArea<M extends BaseShippingArea<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 物流公司
	 */
	public void setShippingCode(java.lang.String shippingCode) {
		set("shipping_code", shippingCode);
	}

	/**
	 * 物流公司
	 */
	public java.lang.String getShippingCode() {
		return getStr("shipping_code");
	}

	/**
	 * 是否关闭：1开启，0关闭
	 */
	public void setIsClose(java.lang.Boolean isClose) {
		set("is_close", isClose);
	}

	/**
	 * 是否关闭：1开启，0关闭
	 */
	public java.lang.Boolean getIsClose() {
		return get("is_close");
	}

	/**
	 * 商家id
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 商家id
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

}
