package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAddress<M extends BaseUserAddress<M>> extends BaseModel<M> implements IBean {

	public void setAddressId(java.lang.Integer addressId) {
		set("address_id", addressId);
	}

	public java.lang.Integer getAddressId() {
		return getInt("address_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 收货人
	 */
	public void setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
	}

	/**
	 * 收货人
	 */
	public java.lang.String getConsignee() {
		return getStr("consignee");
	}

	/**
	 * 邮箱地址
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	/**
	 * 邮箱地址
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}

	/**
	 * 国家
	 */
	public void setCountry(java.lang.Integer country) {
		set("country", country);
	}

	/**
	 * 国家
	 */
	public java.lang.Integer getCountry() {
		return getInt("country");
	}

	/**
	 * 省份
	 */
	public void setProvince(java.lang.Integer province) {
		set("province", province);
	}

	/**
	 * 省份
	 */
	public java.lang.Integer getProvince() {
		return getInt("province");
	}

	/**
	 * 城市
	 */
	public void setCity(java.lang.Integer city) {
		set("city", city);
	}

	/**
	 * 城市
	 */
	public java.lang.Integer getCity() {
		return getInt("city");
	}

	/**
	 * 地区
	 */
	public void setDistrict(java.lang.Integer district) {
		set("district", district);
	}

	/**
	 * 地区
	 */
	public java.lang.Integer getDistrict() {
		return getInt("district");
	}

	/**
	 * 乡镇
	 */
	public void setTwon(java.lang.Integer twon) {
		set("twon", twon);
	}

	/**
	 * 乡镇
	 */
	public java.lang.Integer getTwon() {
		return getInt("twon");
	}

	/**
	 * 地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	/**
	 * 地址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 邮政编码
	 */
	public void setZipcode(java.lang.String zipcode) {
		set("zipcode", zipcode);
	}

	/**
	 * 邮政编码
	 */
	public java.lang.String getZipcode() {
		return getStr("zipcode");
	}

	/**
	 * 手机
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	/**
	 * 手机
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * 默认收货地址
	 */
	public void setIsDefault(java.lang.Integer isDefault) {
		set("is_default", isDefault);
	}

	/**
	 * 默认收货地址
	 */
	public java.lang.Integer getIsDefault() {
		return getInt("is_default");
	}

}
