package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockLog<M extends BaseStockLog<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 商品ID
	 */
	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}

	/**
	 * 商品ID
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 商品名称
	 */
	public void setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
	}

	/**
	 * 商品名称
	 */
	public java.lang.String getGoodsName() {
		return getStr("goods_name");
	}

	/**
	 * 商品规格
	 */
	public void setGoodsSpec(java.lang.String goodsSpec) {
		set("goods_spec", goodsSpec);
	}

	/**
	 * 商品规格
	 */
	public java.lang.String getGoodsSpec() {
		return getStr("goods_spec");
	}

	/**
	 * 订单编号
	 */
	public void setOrderSn(java.lang.String orderSn) {
		set("order_sn", orderSn);
	}

	/**
	 * 订单编号
	 */
	public java.lang.String getOrderSn() {
		return getStr("order_sn");
	}

	/**
	 * 商家ID
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 商家ID
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 操作用户ID
	 */
	public void setMuid(java.lang.Integer muid) {
		set("muid", muid);
	}

	/**
	 * 操作用户ID
	 */
	public java.lang.Integer getMuid() {
		return getInt("muid");
	}

	/**
	 * 更改库存
	 */
	public void setStock(java.lang.Integer stock) {
		set("stock", stock);
	}

	/**
	 * 更改库存
	 */
	public java.lang.Integer getStock() {
		return getInt("stock");
	}

	/**
	 * 操作时间
	 */
	public void setCtime(java.lang.Integer ctime) {
		set("ctime", ctime);
	}

	/**
	 * 操作时间
	 */
	public java.lang.Integer getCtime() {
		return getInt("ctime");
	}

}
