package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserMessage<M extends BaseUserMessage<M>> extends BaseModel<M> implements IBean {

	public void setRecId(java.lang.Integer recId) {
		set("rec_id", recId);
	}

	public java.lang.Integer getRecId() {
		return getInt("rec_id");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 消息id
	 */
	public void setMessageId(java.lang.Long messageId) {
		set("message_id", messageId);
	}

	/**
	 * 消息id
	 */
	public java.lang.Long getMessageId() {
		return getLong("message_id");
	}

	/**
	 * 通知消息：0, 活动消息：1, 物流:2, 私信:3
	 */
	public void setCategory(java.lang.Boolean category) {
		set("category", category);
	}

	/**
	 * 通知消息：0, 活动消息：1, 物流:2, 私信:3
	 */
	public java.lang.Boolean getCategory() {
		return get("category");
	}

	/**
	 * 是否查看：0未查看, 1已查看
	 */
	public void setIsSee(java.lang.Boolean isSee) {
		set("is_see", isSee);
	}

	/**
	 * 是否查看：0未查看, 1已查看
	 */
	public java.lang.Boolean getIsSee() {
		return get("is_see");
	}

	/**
	 * 用户假删除标识,1:删除,0未删除
	 */
	public void setDeleted(java.lang.Boolean deleted) {
		set("deleted", deleted);
	}

	/**
	 * 用户假删除标识,1:删除,0未删除
	 */
	public java.lang.Boolean getDeleted() {
		return get("deleted");
	}

	/**
	 * 查看状态：0未查看，1已查看
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	/**
	 * 查看状态：0未查看，1已查看
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
