package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleOperation<M extends BaseRoleOperation<M>> extends BaseModel<M> implements IBean {

	public void setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
	}

	public java.lang.Integer getRoleId() {
		return getInt("roleId");
	}

	public void setOperateId(java.lang.Integer operateId) {
		set("operateId", operateId);
	}

	public java.lang.Integer getOperateId() {
		return getInt("operateId");
	}

}
