package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGood<M extends BaseGood<M>> extends BaseModel<M> implements IBean {

	/**
	 * 商品id
	 */
	public void setGoodsId(java.lang.Long goodsId) {
		set("goods_id", goodsId);
	}

	/**
	 * 商品id
	 */
	public java.lang.Long getGoodsId() {
		return getLong("goods_id");
	}

	/**
	 * 一级分类id
	 */
	public void setCatId1(java.lang.Integer catId1) {
		set("cat_id1", catId1);
	}

	/**
	 * 一级分类id
	 */
	public java.lang.Integer getCatId1() {
		return getInt("cat_id1");
	}

	/**
	 * 二级分类
	 */
	public void setCatId2(java.lang.Integer catId2) {
		set("cat_id2", catId2);
	}

	/**
	 * 二级分类
	 */
	public java.lang.Integer getCatId2() {
		return getInt("cat_id2");
	}

	/**
	 * 三级分类
	 */
	public void setCatId3(java.lang.Integer catId3) {
		set("cat_id3", catId3);
	}

	/**
	 * 三级分类
	 */
	public java.lang.Integer getCatId3() {
		return getInt("cat_id3");
	}

	/**
	 * 商品分类ID
	 */
	public void setGoodCategoryId(java.lang.Integer goodCategoryId) {
		set("good_category_id", goodCategoryId);
	}

	/**
	 * 商品分类ID
	 */
	public java.lang.Integer getGoodCategoryId() {
		return getInt("good_category_id");
	}

	/**
	 * 商品编号
	 */
	public void setGoodsSn(java.lang.String goodsSn) {
		set("goods_sn", goodsSn);
	}

	/**
	 * 商品编号
	 */
	public java.lang.String getGoodsSn() {
		return getStr("goods_sn");
	}

	/**
	 * 商品名称
	 */
	public void setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
	}

	/**
	 * 商品名称
	 */
	public java.lang.String getGoodsName() {
		return getStr("goods_name");
	}

	/**
	 * 点击数
	 */
	public void setClickCount(java.lang.Integer clickCount) {
		set("click_count", clickCount);
	}

	/**
	 * 点击数
	 */
	public java.lang.Integer getClickCount() {
		return getInt("click_count");
	}

	/**
	 * 品牌id
	 */
	public void setBrandId(java.lang.Long brandId) {
		set("brand_id", brandId);
	}

	/**
	 * 品牌id
	 */
	public java.lang.Long getBrandId() {
		return getLong("brand_id");
	}

	/**
	 * 商品收藏数
	 */
	public void setCollectSum(java.lang.Integer collectSum) {
		set("collect_sum", collectSum);
	}

	/**
	 * 商品收藏数
	 */
	public java.lang.Integer getCollectSum() {
		return getInt("collect_sum");
	}

	/**
	 * 商品评论数
	 */
	public void setCommentCount(java.lang.Integer commentCount) {
		set("comment_count", commentCount);
	}

	/**
	 * 商品评论数
	 */
	public java.lang.Integer getCommentCount() {
		return getInt("comment_count");
	}

	/**
	 * 商品重量克为单位
	 */
	public void setWeight(java.lang.Integer weight) {
		set("weight", weight);
	}

	/**
	 * 商品重量克为单位
	 */
	public java.lang.Integer getWeight() {
		return getInt("weight");
	}

	/**
	 * 商品体积。单位立方米
	 */
	public void setVolume(java.lang.Double volume) {
		set("volume", volume);
	}

	/**
	 * 商品体积。单位立方米
	 */
	public java.lang.Double getVolume() {
		return getDouble("volume");
	}

	/**
	 * COMMENT '积分兑换：0不参与积分兑换
	 */
	public void setExchangeIntegral(java.lang.Integer exchangeIntegral) {
		set("exchange_integral", exchangeIntegral);
	}

	/**
	 * COMMENT '积分兑换：0不参与积分兑换
	 */
	public java.lang.Integer getExchangeIntegral() {
		return getInt("exchange_integral");
	}

	/**
	 * 商品关键词
	 */
	public void setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
	}

	/**
	 * 商品关键词
	 */
	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	/**
	 * 商品简单描述
	 */
	public void setGoodsRemark(java.lang.String goodsRemark) {
		set("goods_remark", goodsRemark);
	}

	/**
	 * 商品简单描述
	 */
	public java.lang.String getGoodsRemark() {
		return getStr("goods_remark");
	}

	/**
	 * 商品详细描述
	 */
	public void setGoodsContent(java.lang.String goodsContent) {
		set("goods_content", goodsContent);
	}

	/**
	 * 商品详细描述
	 */
	public java.lang.String getGoodsContent() {
		return getStr("goods_content");
	}

	/**
	 * 手机端商品详情
	 */
	public void setMobileContent(java.lang.String mobileContent) {
		set("mobile_content", mobileContent);
	}

	/**
	 * 手机端商品详情
	 */
	public java.lang.String getMobileContent() {
		return getStr("mobile_content");
	}

	/**
	 * 商品上传原始图
	 */
	public void setOriginalImg(java.lang.String originalImg) {
		set("original_img", originalImg);
	}

	/**
	 * 商品上传原始图
	 */
	public java.lang.String getOriginalImg() {
		return getStr("original_img");
	}

	/**
	 * 是否为虚拟商品 1是，0否
	 */
	public void setIsVirtual(java.lang.Integer isVirtual) {
		set("is_virtual", isVirtual);
	}

	/**
	 * 是否为虚拟商品 1是，0否
	 */
	public java.lang.Integer getIsVirtual() {
		return getInt("is_virtual");
	}

	/**
	 * 虚拟商品有效期
	 */
	public void setVirtualIndate(java.lang.Integer virtualIndate) {
		set("virtual_indate", virtualIndate);
	}

	/**
	 * 虚拟商品有效期
	 */
	public java.lang.Integer getVirtualIndate() {
		return getInt("virtual_indate");
	}

	/**
	 * 虚拟商品购买上限
	 */
	public void setVirtualLimit(java.lang.Integer virtualLimit) {
		set("virtual_limit", virtualLimit);
	}

	/**
	 * 虚拟商品购买上限
	 */
	public java.lang.Integer getVirtualLimit() {
		return getInt("virtual_limit");
	}

	/**
	 * 是否允许过期退款， 1是，0否
	 */
	public void setVirtualRefund(java.lang.Integer virtualRefund) {
		set("virtual_refund", virtualRefund);
	}

	/**
	 * 是否允许过期退款， 1是，0否
	 */
	public java.lang.Integer getVirtualRefund() {
		return getInt("virtual_refund");
	}

	/**
	 * 0下架1上架2违规下架
	 */
	public void setIsOnSale(java.lang.Integer isOnSale) {
		set("is_on_sale", isOnSale);
	}

	/**
	 * 0下架1上架2违规下架
	 */
	public java.lang.Integer getIsOnSale() {
		return getInt("is_on_sale");
	}

	/**
	 * 是否包邮0否1是
	 */
	public void setIsFreeShipping(java.lang.Integer isFreeShipping) {
		set("is_free_shipping", isFreeShipping);
	}

	/**
	 * 是否包邮0否1是
	 */
	public java.lang.Integer getIsFreeShipping() {
		return getInt("is_free_shipping");
	}

	/**
	 * 商品上架时间
	 */
	public void setOnTime(java.lang.Long onTime) {
		set("on_time", onTime);
	}

	/**
	 * 商品上架时间
	 */
	public java.lang.Long getOnTime() {
		return getLong("on_time");
	}

	/**
	 * 商品排序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	/**
	 * 商品排序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 是否推荐(1是，0否)
	 */
	public void setIsRecommend(java.lang.Integer isRecommend) {
		set("is_recommend", isRecommend);
	}

	/**
	 * 是否推荐(1是，0否)
	 */
	public java.lang.Integer getIsRecommend() {
		return getInt("is_recommend");
	}

	/**
	 * 是否新品
	 */
	public void setIsNew(java.lang.Long isNew) {
		set("is_new", isNew);
	}

	/**
	 * 是否新品
	 */
	public java.lang.Long getIsNew() {
		return getLong("is_new");
	}

	/**
	 * 是否热卖
	 */
	public void setIsHot(java.lang.Integer isHot) {
		set("is_hot", isHot);
	}

	/**
	 * 是否热卖
	 */
	public java.lang.Integer getIsHot() {
		return getInt("is_hot");
	}

	/**
	 * 购买商品赠送积分
	 */
	public void setGiveIntegral(java.lang.Integer giveIntegral) {
		set("give_integral", giveIntegral);
	}

	/**
	 * 购买商品赠送积分
	 */
	public java.lang.Integer getGiveIntegral() {
		return getInt("give_integral");
	}

	/**
	 * 商品销量
	 */
	public void setSalesSum(java.lang.Integer salesSum) {
		set("sales_sum", salesSum);
	}

	/**
	 * 商品销量
	 */
	public java.lang.Integer getSalesSum() {
		return getInt("sales_sum");
	}

	/**
	 * 0默认1抢购2团购3优惠促销4预售5虚拟(5其实没用)6拼团
	 */
	public void setPromType(java.lang.Integer promType) {
		set("prom_type", promType);
	}

	/**
	 * 0默认1抢购2团购3优惠促销4预售5虚拟(5其实没用)6拼团
	 */
	public java.lang.Integer getPromType() {
		return getInt("prom_type");
	}

	/**
	 * 优惠活动id
	 */
	public void setPromId(java.lang.Integer promId) {
		set("prom_id", promId);
	}

	/**
	 * 优惠活动id
	 */
	public java.lang.Integer getPromId() {
		return getInt("prom_id");
	}

	/**
	 * 商家店铺ID
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 商家店铺ID
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * SPU
	 */
	public void setSpu(java.lang.String spu) {
		set("spu", spu);
	}

	/**
	 * SPU
	 */
	public java.lang.String getSpu() {
		return getStr("spu");
	}

	/**
	 * SKU
	 */
	public void setSku(java.lang.String sku) {
		set("sku", sku);
	}

	/**
	 * SKU
	 */
	public java.lang.String getSku() {
		return getStr("sku");
	}

	/**
	 * 0待审核1审核通过2审核失败
	 */
	public void setGoodsState(java.lang.Integer goodsState) {
		set("goods_state", goodsState);
	}

	/**
	 * 0待审核1审核通过2审核失败
	 */
	public java.lang.Integer getGoodsState() {
		return getInt("goods_state");
	}

	/**
	 * 审核失败原因
	 */
	public void setGoodsReason(java.lang.String goodsReason) {
		set("goods_reason", goodsReason);
	}

	/**
	 * 审核失败原因
	 */
	public java.lang.String getGoodsReason() {
		return getStr("goods_reason");
	}

	/**
	 * 违规下架原因
	 */
	public void setCloseReason(java.lang.String closeReason) {
		set("close_reason", closeReason);
	}

	/**
	 * 违规下架原因
	 */
	public java.lang.String getCloseReason() {
		return getStr("close_reason");
	}

	/**
	 * 运费模板ID
	 */
	public void setTemplateId(java.lang.Long templateId) {
		set("template_id", templateId);
	}

	/**
	 * 运费模板ID
	 */
	public java.lang.Long getTemplateId() {
		return getLong("template_id");
	}

	/**
	 * 视频地址
	 */
	public void setVideo(java.lang.String video) {
		set("video", video);
	}

	/**
	 * 视频地址
	 */
	public java.lang.String getVideo() {
		return getStr("video");
	}

	/**
	 * 是否需要上门服务（1.无需上门服务;2.可选上门服务;3.必须上门服务）
	 */
	public void setDoorServiceStatus(java.lang.Integer doorServiceStatus) {
		set("door_service_status", doorServiceStatus);
	}

	/**
	 * 是否需要上门服务（1.无需上门服务;2.可选上门服务;3.必须上门服务）
	 */
	public java.lang.Integer getDoorServiceStatus() {
		return getInt("door_service_status");
	}

	/**
	 * 冗余店铺推广比例
	 */
	public void setStorePromoteRate(java.math.BigDecimal storePromoteRate) {
		set("store_promote_rate", storePromoteRate);
	}

	/**
	 * 冗余店铺推广比例
	 */
	public java.math.BigDecimal getStorePromoteRate() {
		return get("store_promote_rate");
	}

	/**
	 * 0否 1是
	 */
	public void setIsEarnPoint(java.lang.Integer isEarnPoint) {
		set("is_earn_point", isEarnPoint);
	}

	/**
	 * 0否 1是
	 */
	public java.lang.Integer getIsEarnPoint() {
		return getInt("is_earn_point");
	}

	/**
	 * 最多可以使用多少额度积分抵扣金额
	 */
	public void setPointAsMoney(java.math.BigDecimal pointAsMoney) {
		set("point_as_money", pointAsMoney);
	}

	/**
	 * 最多可以使用多少额度积分抵扣金额
	 */
	public java.math.BigDecimal getPointAsMoney() {
		return get("point_as_money");
	}

}
