package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStoreGoodsClass<M extends BaseStoreGoodsClass<M>> extends BaseModel<M> implements IBean {

	/**
	 * 索引ID
	 */
	public void setCatId(java.lang.Integer catId) {
		set("cat_id", catId);
	}

	/**
	 * 索引ID
	 */
	public java.lang.Integer getCatId() {
		return getInt("cat_id");
	}

	/**
	 * 店铺商品分类名称
	 */
	public void setCatName(java.lang.String catName) {
		set("cat_name", catName);
	}

	/**
	 * 店铺商品分类名称
	 */
	public java.lang.String getCatName() {
		return getStr("cat_name");
	}

	/**
	 * 父级id
	 */
	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}

	/**
	 * 父级id
	 */
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	/**
	 * 店铺id
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 店铺id
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 商品分类排序
	 */
	public void setCatSort(java.lang.Integer catSort) {
		set("cat_sort", catSort);
	}

	/**
	 * 商品分类排序
	 */
	public java.lang.Integer getCatSort() {
		return getInt("cat_sort");
	}

	/**
	 * 分类显示状态
	 */
	public void setIsShow(java.lang.Boolean isShow) {
		set("is_show", isShow);
	}

	/**
	 * 分类显示状态
	 */
	public java.lang.Boolean getIsShow() {
		return get("is_show");
	}

	/**
	 * 是否显示在导航栏
	 */
	public void setIsNavShow(java.lang.Boolean isNavShow) {
		set("is_nav_show", isNavShow);
	}

	/**
	 * 是否显示在导航栏
	 */
	public java.lang.Boolean getIsNavShow() {
		return get("is_nav_show");
	}

	/**
	 * 是否首页推荐
	 */
	public void setIsRecommend(java.lang.Boolean isRecommend) {
		set("is_recommend", isRecommend);
	}

	/**
	 * 是否首页推荐
	 */
	public java.lang.Boolean getIsRecommend() {
		return get("is_recommend");
	}

	/**
	 * 首页此类商品显示数量
	 */
	public void setShowNum(java.lang.Integer showNum) {
		set("show_num", showNum);
	}

	/**
	 * 首页此类商品显示数量
	 */
	public java.lang.Integer getShowNum() {
		return getInt("show_num");
	}

}
