package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHomeSet<M extends BaseHomeSet<M>> extends BaseModel<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	/**
	 * 标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 类型（1资讯2商品详情3商品分类4WEB地址5店铺首页6专题页7推荐店铺8邀请有礼9拼团抽奖10秒杀）
	 */
	public void setGotoType(java.lang.Integer gotoType) {
		set("goto_type", gotoType);
	}

	/**
	 * 类型（1资讯2商品详情3商品分类4WEB地址5店铺首页6专题页7推荐店铺8邀请有礼9拼团抽奖10秒杀）
	 */
	public java.lang.Integer getGotoType() {
		return getInt("goto_type");
	}

	/**
	 * 跳转页面对应业务ID
	 */
	public void setGotoId(java.lang.Integer gotoId) {
		set("goto_id", gotoId);
	}

	/**
	 * 跳转页面对应业务ID
	 */
	public java.lang.Integer getGotoId() {
		return getInt("goto_id");
	}

	/**
	 * 位置（1banner2金刚区3资讯区4打广告5小广告6专场
	 */
	public void setPosition(java.lang.Integer position) {
		set("position", position);
	}

	/**
	 * 位置（1banner2金刚区3资讯区4打广告5小广告6专场
	 */
	public java.lang.Integer getPosition() {
		return getInt("position");
	}

	/**
	 * 排序
	 */
	public void setSortId(java.lang.Integer sortId) {
		set("sort_id", sortId);
	}

	/**
	 * 排序
	 */
	public java.lang.Integer getSortId() {
		return getInt("sort_id");
	}

	/**
	 * 图片地址
	 */
	public void setImg(java.lang.String img) {
		set("img", img);
	}

	/**
	 * 图片地址
	 */
	public java.lang.String getImg() {
		return getStr("img");
	}

	/**
	 * 跳转WEB地址
	 */
	public void setWebUrl(java.lang.String webUrl) {
		set("web_url", webUrl);
	}

	/**
	 * 跳转WEB地址
	 */
	public java.lang.String getWebUrl() {
		return getStr("web_url");
	}

	/**
	 * 背景颜色
	 */
	public void setBackgroundColor(java.lang.String backgroundColor) {
		set("background_color", backgroundColor);
	}

	/**
	 * 背景颜色
	 */
	public java.lang.String getBackgroundColor() {
		return getStr("background_color");
	}

	/**
	 * 是否显示(1显示2不显示)
	 */
	public void setIsShow(java.lang.Integer isShow) {
		set("is_show", isShow);
	}

	/**
	 * 是否显示(1显示2不显示)
	 */
	public java.lang.Integer getIsShow() {
		return getInt("is_show");
	}

	/**
	 * 子块对应的父块的ID
	 */
	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}

	/**
	 * 子块对应的父块的ID
	 */
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
