package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSmsTemplate<M extends BaseSmsTemplate<M>> extends BaseModel<M> implements IBean {

	/**
	 * 自增ID
	 */
	public void setTplId(java.lang.Integer tplId) {
		set("tpl_id", tplId);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getTplId() {
		return getInt("tpl_id");
	}

	/**
	 * 短信签名
	 */
	public void setSmsSign(java.lang.String smsSign) {
		set("sms_sign", smsSign);
	}

	/**
	 * 短信签名
	 */
	public java.lang.String getSmsSign() {
		return getStr("sms_sign");
	}

	/**
	 * 短信模板ID
	 */
	public void setSmsTplCode(java.lang.String smsTplCode) {
		set("sms_tpl_code", smsTplCode);
	}

	/**
	 * 短信模板ID
	 */
	public java.lang.String getSmsTplCode() {
		return getStr("sms_tpl_code");
	}

	/**
	 * 发送短信内容
	 */
	public void setTplContent(java.lang.String tplContent) {
		set("tpl_content", tplContent);
	}

	/**
	 * 发送短信内容
	 */
	public java.lang.String getTplContent() {
		return getStr("tpl_content");
	}

	/**
	 * 短信发送场景
	 */
	public void setSendScene(java.lang.String sendScene) {
		set("send_scene", sendScene);
	}

	/**
	 * 短信发送场景
	 */
	public java.lang.String getSendScene() {
		return getStr("send_scene");
	}

	/**
	 * 添加时间
	 */
	public void setAddTime(java.lang.Integer addTime) {
		set("add_time", addTime);
	}

	/**
	 * 添加时间
	 */
	public java.lang.Integer getAddTime() {
		return getInt("add_time");
	}

}
