package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserMsgTpl<M extends BaseUserMsgTpl<M>> extends BaseModel<M> implements IBean {

	/**
	 * 用户消息模板编号
	 */
	public void setMmtCode(java.lang.String mmtCode) {
		set("mmt_code", mmtCode);
	}

	/**
	 * 用户消息模板编号
	 */
	public java.lang.String getMmtCode() {
		return getStr("mmt_code");
	}

	/**
	 * 模板名称
	 */
	public void setMmtName(java.lang.String mmtName) {
		set("mmt_name", mmtName);
	}

	/**
	 * 模板名称
	 */
	public java.lang.String getMmtName() {
		return getStr("mmt_name");
	}

	/**
	 * 站内信接收开关
	 */
	public void setMmtMessageSwitch(java.lang.Integer mmtMessageSwitch) {
		set("mmt_message_switch", mmtMessageSwitch);
	}

	/**
	 * 站内信接收开关
	 */
	public java.lang.Integer getMmtMessageSwitch() {
		return getInt("mmt_message_switch");
	}

	/**
	 * 站内信消息内容
	 */
	public void setMmtMessageContent(java.lang.String mmtMessageContent) {
		set("mmt_message_content", mmtMessageContent);
	}

	/**
	 * 站内信消息内容
	 */
	public java.lang.String getMmtMessageContent() {
		return getStr("mmt_message_content");
	}

	/**
	 * 短信接收开关
	 */
	public void setMmtShortSwitch(java.lang.Integer mmtShortSwitch) {
		set("mmt_short_switch", mmtShortSwitch);
	}

	/**
	 * 短信接收开关
	 */
	public java.lang.Integer getMmtShortSwitch() {
		return getInt("mmt_short_switch");
	}

	/**
	 * 短信接收内容
	 */
	public void setMmtShortContent(java.lang.String mmtShortContent) {
		set("mmt_short_content", mmtShortContent);
	}

	/**
	 * 短信接收内容
	 */
	public java.lang.String getMmtShortContent() {
		return getStr("mmt_short_content");
	}

	/**
	 * 短信签名
	 */
	public void setMmtShortSign(java.lang.String mmtShortSign) {
		set("mmt_short_sign", mmtShortSign);
	}

	/**
	 * 短信签名
	 */
	public java.lang.String getMmtShortSign() {
		return getStr("mmt_short_sign");
	}

	/**
	 * 短信模板ID
	 */
	public void setMmtShortCode(java.lang.String mmtShortCode) {
		set("mmt_short_code", mmtShortCode);
	}

	/**
	 * 短信模板ID
	 */
	public java.lang.String getMmtShortCode() {
		return getStr("mmt_short_code");
	}

	/**
	 * 邮件接收开关
	 */
	public void setMmtMailSwitch(java.lang.Integer mmtMailSwitch) {
		set("mmt_mail_switch", mmtMailSwitch);
	}

	/**
	 * 邮件接收开关
	 */
	public java.lang.Integer getMmtMailSwitch() {
		return getInt("mmt_mail_switch");
	}

	/**
	 * 邮件标题
	 */
	public void setMmtMailSubject(java.lang.String mmtMailSubject) {
		set("mmt_mail_subject", mmtMailSubject);
	}

	/**
	 * 邮件标题
	 */
	public java.lang.String getMmtMailSubject() {
		return getStr("mmt_mail_subject");
	}

	/**
	 * 邮件内容
	 */
	public void setMmtMailContent(java.lang.String mmtMailContent) {
		set("mmt_mail_content", mmtMailContent);
	}

	/**
	 * 邮件内容
	 */
	public java.lang.String getMmtMailContent() {
		return getStr("mmt_mail_content");
	}

}
