package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 类别ID
	 */
	public void setCatId(java.lang.Integer catId) {
		set("cat_id", catId);
	}

	/**
	 * 类别ID
	 */
	public java.lang.Integer getCatId() {
		return getInt("cat_id");
	}

	/**
	 * 文章标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	/**
	 * 文章标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 文章作者
	 */
	public void setAuthor(java.lang.String author) {
		set("author", author);
	}

	/**
	 * 文章作者
	 */
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	/**
	 * 关键字
	 */
	public void setKeyword(java.lang.String keyword) {
		set("keyword", keyword);
	}

	/**
	 * 关键字
	 */
	public java.lang.String getKeyword() {
		return getStr("keyword");
	}

	/**
	 * 文章缩略图
	 */
	public void setThumb(java.lang.String thumb) {
		set("thumb", thumb);
	}

	/**
	 * 文章缩略图
	 */
	public java.lang.String getThumb() {
		return getStr("thumb");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 浏览量
	 */
	public void setClick(java.lang.Integer click) {
		set("click", click);
	}

	/**
	 * 浏览量
	 */
	public java.lang.Integer getClick() {
		return getInt("click");
	}

	/**
	 * 新增时间 
	 */
	public void setAddTime(java.util.Date addTime) {
		set("add_time", addTime);
	}

	/**
	 * 新增时间 
	 */
	public java.util.Date getAddTime() {
		return get("add_time");
	}

}
