package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCouponBusiness<M extends BaseCouponBusiness<M>> extends BaseModel<M> implements IBean {

	/**
	 * 自增长ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增长ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 优惠券活动ID
	 */
	public void setActivityId(java.lang.Integer activityId) {
		set("activity_id", activityId);
	}

	/**
	 * 优惠券活动ID
	 */
	public java.lang.Integer getActivityId() {
		return getInt("activity_id");
	}

	/**
	 * 使用范围 1：针对单品、2：针对分类、3：针对品牌、4：针对全平台所有商品、5:：针对制定店铺
	 */
	public void setUseType(java.lang.Integer useType) {
		set("use_type", useType);
	}

	/**
	 * 使用范围 1：针对单品、2：针对分类、3：针对品牌、4：针对全平台所有商品、5:：针对制定店铺
	 */
	public java.lang.Integer getUseType() {
		return getInt("use_type");
	}

	/**
	 * 对应的业务id
	 */
	public void setBusinessId(java.lang.Integer businessId) {
		set("business_id", businessId);
	}

	/**
	 * 对应的业务id
	 */
	public java.lang.Integer getBusinessId() {
		return getInt("business_id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
