package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStoreCollect<M extends BaseStoreCollect<M>> extends BaseModel<M> implements IBean {

	public void setLogId(java.lang.Long logId) {
		set("log_id", logId);
	}

	public java.lang.Long getLogId() {
		return getLong("log_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 收藏店铺时间
	 */
	public void setAddTime(java.lang.Integer addTime) {
		set("add_time", addTime);
	}

	/**
	 * 收藏店铺时间
	 */
	public java.lang.Integer getAddTime() {
		return getInt("add_time");
	}

	public void setStoreName(java.lang.String storeName) {
		set("store_name", storeName);
	}

	public java.lang.String getStoreName() {
		return getStr("store_name");
	}

	/**
	 * 收藏会员名称
	 */
	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	/**
	 * 收藏会员名称
	 */
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

}
