package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReturnGoods<M extends BaseReturnGoods<M>> extends BaseModel<M> implements IBean {

	/**
	 * 退货申请表id自增
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 退货申请表id自增
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 对应订单商品表ID
	 */
	public void setRecId(java.lang.Integer recId) {
		set("rec_id", recId);
	}

	/**
	 * 对应订单商品表ID
	 */
	public java.lang.Integer getRecId() {
		return getInt("rec_id");
	}

	/**
	 * 订单id
	 */
	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}

	/**
	 * 订单id
	 */
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 订单编号
	 */
	public void setOrderSn(java.lang.String orderSn) {
		set("order_sn", orderSn);
	}

	/**
	 * 订单编号
	 */
	public java.lang.String getOrderSn() {
		return getStr("order_sn");
	}

	/**
	 * 商品id
	 */
	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}

	/**
	 * 商品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 退货数量
	 */
	public void setGoodsNum(java.lang.Integer goodsNum) {
		set("goods_num", goodsNum);
	}

	/**
	 * 退货数量
	 */
	public java.lang.Integer getGoodsNum() {
		return getInt("goods_num");
	}

	/**
	 * 0仅退款 1退货退款  2换货 3维修
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	/**
	 * 0仅退款 1退货退款  2换货 3维修
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 退换货退款申请原因
	 */
	public void setReason(java.lang.String reason) {
		set("reason", reason);
	}

	/**
	 * 退换货退款申请原因
	 */
	public java.lang.String getReason() {
		return getStr("reason");
	}

	/**
	 * 问题描述
	 */
	public void setDescribe(java.lang.String describe) {
		set("describe", describe);
	}

	/**
	 * 问题描述
	 */
	public java.lang.String getDescribe() {
		return getStr("describe");
	}

	/**
	 * 申请凭据
	 */
	public void setEvidence(java.lang.String evidence) {
		set("evidence", evidence);
	}

	/**
	 * 申请凭据
	 */
	public java.lang.String getEvidence() {
		return getStr("evidence");
	}

	/**
	 * 上传图片路径
	 */
	public void setImgs(java.lang.String imgs) {
		set("imgs", imgs);
	}

	/**
	 * 上传图片路径
	 */
	public java.lang.String getImgs() {
		return getStr("imgs");
	}

	/**
	 * -2用户取消-1不同意0待审核1通过2已发货3待退款4换货完成5退款完成6申诉仲裁
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	/**
	 * -2用户取消-1不同意0待审核1通过2已发货3待退款4换货完成5退款完成6申诉仲裁
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 卖家审核进度说明
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	/**
	 * 卖家审核进度说明
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 商家店铺ID
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 商家店铺ID
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 商品规格
	 */
	public void setSpecKey(java.lang.String specKey) {
		set("spec_key", specKey);
	}

	/**
	 * 商品规格
	 */
	public java.lang.String getSpecKey() {
		return getStr("spec_key");
	}

	/**
	 * 客户姓名
	 */
	public void setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
	}

	/**
	 * 客户姓名
	 */
	public java.lang.String getConsignee() {
		return getStr("consignee");
	}

	/**
	 * 手机号码
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	/**
	 * 手机号码
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * 收货地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	/**
	 * 收货地址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 退还积分
	 */
	public void setRefundIntegral(java.lang.Integer refundIntegral) {
		set("refund_integral", refundIntegral);
	}

	/**
	 * 退还积分
	 */
	public java.lang.Integer getRefundIntegral() {
		return getInt("refund_integral");
	}

	/**
	 * 退还预存款
	 */
	public void setRefundDeposit(java.math.BigDecimal refundDeposit) {
		set("refund_deposit", refundDeposit);
	}

	/**
	 * 退还预存款
	 */
	public java.math.BigDecimal getRefundDeposit() {
		return get("refund_deposit");
	}

	/**
	 * 退款金额
	 */
	public void setRefundMoney(java.math.BigDecimal refundMoney) {
		set("refund_money", refundMoney);
	}

	/**
	 * 退款金额
	 */
	public java.math.BigDecimal getRefundMoney() {
		return get("refund_money");
	}

	/**
	 * 0退到用户余额 1支付原路退回
	 */
	public void setRefundType(java.lang.Integer refundType) {
		set("refund_type", refundType);
	}

	/**
	 * 0退到用户余额 1支付原路退回
	 */
	public java.lang.Integer getRefundType() {
		return getInt("refund_type");
	}

	/**
	 * 管理员退款备注
	 */
	public void setRefundMark(java.lang.String refundMark) {
		set("refund_mark", refundMark);
	}

	/**
	 * 管理员退款备注
	 */
	public java.lang.String getRefundMark() {
		return getStr("refund_mark");
	}

	/**
	 * 退款时间
	 */
	public void setRefundTime(java.lang.Integer refundTime) {
		set("refund_time", refundTime);
	}

	/**
	 * 退款时间
	 */
	public java.lang.Integer getRefundTime() {
		return getInt("refund_time");
	}

	/**
	 * 售后申请时间
	 */
	public void setAddtime(java.lang.Integer addtime) {
		set("addtime", addtime);
	}

	/**
	 * 售后申请时间
	 */
	public java.lang.Integer getAddtime() {
		return getInt("addtime");
	}

	/**
	 * 卖家审核时间
	 */
	public void setChecktime(java.lang.Integer checktime) {
		set("checktime", checktime);
	}

	/**
	 * 卖家审核时间
	 */
	public java.lang.Integer getChecktime() {
		return getInt("checktime");
	}

	/**
	 * 卖家收货时间
	 */
	public void setReceivetime(java.lang.Integer receivetime) {
		set("receivetime", receivetime);
	}

	/**
	 * 卖家收货时间
	 */
	public java.lang.Integer getReceivetime() {
		return getInt("receivetime");
	}

	/**
	 * 用户取消时间
	 */
	public void setCanceltime(java.lang.Integer canceltime) {
		set("canceltime", canceltime);
	}

	/**
	 * 用户取消时间
	 */
	public java.lang.Integer getCanceltime() {
		return getInt("canceltime");
	}

	/**
	 * 换货服务，卖家重新发货信息
	 */
	public void setSellerDelivery(java.lang.String sellerDelivery) {
		set("seller_delivery", sellerDelivery);
	}

	/**
	 * 换货服务，卖家重新发货信息
	 */
	public java.lang.String getSellerDelivery() {
		return getStr("seller_delivery");
	}

	/**
	 * 用户发货信息
	 */
	public void setDelivery(java.lang.String delivery) {
		set("delivery", delivery);
	}

	/**
	 * 用户发货信息
	 */
	public java.lang.String getDelivery() {
		return getStr("delivery");
	}

	/**
	 * 退款差额
	 */
	public void setGap(java.math.BigDecimal gap) {
		set("gap", gap);
	}

	/**
	 * 退款差额
	 */
	public java.math.BigDecimal getGap() {
		return get("gap");
	}

	/**
	 * 差额原因
	 */
	public void setGapReason(java.lang.String gapReason) {
		set("gap_reason", gapReason);
	}

	/**
	 * 差额原因
	 */
	public java.lang.String getGapReason() {
		return getStr("gap_reason");
	}

	/**
	 * 申请售后时是否已收货0未收货1已收货
	 */
	public void setIsReceive(java.lang.Integer isReceive) {
		set("is_receive", isReceive);
	}

	/**
	 * 申请售后时是否已收货0未收货1已收货
	 */
	public java.lang.Integer getIsReceive() {
		return getInt("is_receive");
	}

}
