package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSmsLog<M extends BaseSmsLog<M>> extends BaseModel<M> implements IBean {

	/**
	 * 表id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 表id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 手机号
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	/**
	 * 手机号
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * session_id
	 */
	public void setSessionId(java.lang.String sessionId) {
		set("session_id", sessionId);
	}

	/**
	 * session_id
	 */
	public java.lang.String getSessionId() {
		return getStr("session_id");
	}

	/**
	 * 发送时间
	 */
	public void setAddTime(java.lang.Integer addTime) {
		set("add_time", addTime);
	}

	/**
	 * 发送时间
	 */
	public java.lang.Integer getAddTime() {
		return getInt("add_time");
	}

	/**
	 * 验证码
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}

	/**
	 * 验证码
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setSellerId(java.lang.Integer sellerId) {
		set("seller_id", sellerId);
	}

	public java.lang.Integer getSellerId() {
		return getInt("seller_id");
	}

	/**
	 * 1:发送成功,0:发送失败
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	/**
	 * 1:发送成功,0:发送失败
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 短信内容
	 */
	public void setMsg(java.lang.String msg) {
		set("msg", msg);
	}

	/**
	 * 短信内容
	 */
	public java.lang.String getMsg() {
		return getStr("msg");
	}

	/**
	 * 发送场景,1:用户注册,2:找回密码,3:客户下单,4:客户支付,5:商家发货,6:身份验证
	 */
	public void setScene(java.lang.Integer scene) {
		set("scene", scene);
	}

	/**
	 * 发送场景,1:用户注册,2:找回密码,3:客户下单,4:客户支付,5:商家发货,6:身份验证
	 */
	public java.lang.Integer getScene() {
		return getInt("scene");
	}

	/**
	 * 发送短信异常内容
	 */
	public void setErrorMsg(java.lang.String errorMsg) {
		set("error_msg", errorMsg);
	}

	/**
	 * 发送短信异常内容
	 */
	public java.lang.String getErrorMsg() {
		return getStr("error_msg");
	}

}
