package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStore<M extends BaseStore<M>> extends BaseModel<M> implements IBean {

	/**
	 * 店铺索引id
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 店铺索引id
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 店铺名称
	 */
	public void setStoreName(java.lang.String storeName) {
		set("store_name", storeName);
	}

	/**
	 * 店铺名称
	 */
	public java.lang.String getStoreName() {
		return getStr("store_name");
	}

	/**
	 * 店铺等级(作废)
	 */
	public void setGradeId(java.lang.Integer gradeId) {
		set("grade_id", gradeId);
	}

	/**
	 * 店铺等级(作废)
	 */
	public java.lang.Integer getGradeId() {
		return getInt("grade_id");
	}

	/**
	 * 会员id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	/**
	 * 会员id
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 会员名称(作废)
	 */
	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	/**
	 * 会员名称(作废)
	 */
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	/**
	 * 店主卖家用户名(作废)
	 */
	public void setSellerName(java.lang.String sellerName) {
		set("seller_name", sellerName);
	}

	/**
	 * 店主卖家用户名(作废)
	 */
	public java.lang.String getSellerName() {
		return getStr("seller_name");
	}

	/**
	 * 店铺分类(作废)
	 */
	public void setScId(java.lang.Integer scId) {
		set("sc_id", scId);
	}

	/**
	 * 店铺分类(作废)
	 */
	public java.lang.Integer getScId() {
		return getInt("sc_id");
	}

	/**
	 * 店铺公司名称(作废)
	 */
	public void setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
	}

	/**
	 * 店铺公司名称(作废)
	 */
	public java.lang.String getCompanyName() {
		return getStr("company_name");
	}

	/**
	 * 店铺所在区域ID
	 */
	public void setRegionId(java.lang.Integer regionId) {
		set("region_id", regionId);
	}

	/**
	 * 店铺所在区域ID
	 */
	public java.lang.Integer getRegionId() {
		return getInt("region_id");
	}

	/**
	 * 店铺所在省份ID(作废)
	 */
	public void setProvinceId(java.lang.Integer provinceId) {
		set("province_id", provinceId);
	}

	/**
	 * 店铺所在省份ID(作废)
	 */
	public java.lang.Integer getProvinceId() {
		return getInt("province_id");
	}

	/**
	 * 店铺所在城市ID(作废)
	 */
	public void setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
	}

	/**
	 * 店铺所在城市ID(作废)
	 */
	public java.lang.Integer getCityId() {
		return getInt("city_id");
	}

	/**
	 * 店铺所在地区ID(作废)
	 */
	public void setDistrict(java.lang.Integer district) {
		set("district", district);
	}

	/**
	 * 店铺所在地区ID(作废)
	 */
	public java.lang.Integer getDistrict() {
		return getInt("district");
	}

	/**
	 * 详细地区
	 */
	public void setStoreAddress(java.lang.String storeAddress) {
		set("store_address", storeAddress);
	}

	/**
	 * 详细地区
	 */
	public java.lang.String getStoreAddress() {
		return getStr("store_address");
	}

	/**
	 * 商家地址经度
	 */
	public void setLongitude(java.math.BigDecimal longitude) {
		set("longitude", longitude);
	}

	/**
	 * 商家地址经度
	 */
	public java.math.BigDecimal getLongitude() {
		return get("longitude");
	}

	/**
	 * 商家地址纬度
	 */
	public void setLatitude(java.math.BigDecimal latitude) {
		set("latitude", latitude);
	}

	/**
	 * 商家地址纬度
	 */
	public java.math.BigDecimal getLatitude() {
		return get("latitude");
	}

	/**
	 * 邮政编码
	 */
	public void setStoreZip(java.lang.String storeZip) {
		set("store_zip", storeZip);
	}

	/**
	 * 邮政编码
	 */
	public java.lang.String getStoreZip() {
		return getStr("store_zip");
	}

	/**
	 * 店铺状态，0关闭，1开启，2审核中
	 */
	public void setStoreState(java.lang.Integer storeState) {
		set("store_state", storeState);
	}

	/**
	 * 店铺状态，0关闭，1开启，2审核中
	 */
	public java.lang.Integer getStoreState() {
		return getInt("store_state");
	}

	/**
	 * 店铺关闭原因
	 */
	public void setStoreCloseInfo(java.lang.String storeCloseInfo) {
		set("store_close_info", storeCloseInfo);
	}

	/**
	 * 店铺关闭原因
	 */
	public java.lang.String getStoreCloseInfo() {
		return getStr("store_close_info");
	}

	/**
	 * 店铺排序(作废)
	 */
	public void setStoreSort(java.lang.Integer storeSort) {
		set("store_sort", storeSort);
	}

	/**
	 * 店铺排序(作废)
	 */
	public java.lang.Integer getStoreSort() {
		return getInt("store_sort");
	}

	/**
	 * 店铺结算类型(作废)
	 */
	public void setStoreRebatePaytime(java.lang.String storeRebatePaytime) {
		set("store_rebate_paytime", storeRebatePaytime);
	}

	/**
	 * 店铺结算类型(作废)
	 */
	public java.lang.String getStoreRebatePaytime() {
		return getStr("store_rebate_paytime");
	}

	/**
	 * 开店时间
	 */
	public void setStoreTime(java.lang.Integer storeTime) {
		set("store_time", storeTime);
	}

	/**
	 * 开店时间
	 */
	public java.lang.Integer getStoreTime() {
		return getInt("store_time");
	}

	/**
	 * 店铺有效截止时间
	 */
	public void setStoreEndTime(java.lang.Integer storeEndTime) {
		set("store_end_time", storeEndTime);
	}

	/**
	 * 店铺有效截止时间
	 */
	public java.lang.Integer getStoreEndTime() {
		return getInt("store_end_time");
	}

	/**
	 * 店铺logo
	 */
	public void setStoreLogo(java.lang.String storeLogo) {
		set("store_logo", storeLogo);
	}

	/**
	 * 店铺logo
	 */
	public java.lang.String getStoreLogo() {
		return getStr("store_logo");
	}

	/**
	 * 店铺横幅
	 */
	public void setStoreBanner(java.lang.String storeBanner) {
		set("store_banner", storeBanner);
	}

	/**
	 * 店铺横幅
	 */
	public java.lang.String getStoreBanner() {
		return getStr("store_banner");
	}

	/**
	 * 店铺头像
	 */
	public void setStoreAvatar(java.lang.String storeAvatar) {
		set("store_avatar", storeAvatar);
	}

	/**
	 * 店铺头像
	 */
	public java.lang.String getStoreAvatar() {
		return getStr("store_avatar");
	}

	/**
	 * 店铺seo关键字(作废)
	 */
	public void setSeoKeywords(java.lang.String seoKeywords) {
		set("seo_keywords", seoKeywords);
	}

	/**
	 * 店铺seo关键字(作废)
	 */
	public java.lang.String getSeoKeywords() {
		return getStr("seo_keywords");
	}

	/**
	 * 店铺seo描述(作废)
	 */
	public void setSeoDescription(java.lang.String seoDescription) {
		set("seo_description", seoDescription);
	}

	/**
	 * 店铺seo描述(作废)
	 */
	public java.lang.String getSeoDescription() {
		return getStr("seo_description");
	}

	/**
	 * 阿里旺旺(作废)
	 */
	public void setStoreAliwangwang(java.lang.String storeAliwangwang) {
		set("store_aliwangwang", storeAliwangwang);
	}

	/**
	 * 阿里旺旺(作废)
	 */
	public java.lang.String getStoreAliwangwang() {
		return getStr("store_aliwangwang");
	}

	/**
	 * QQ(作废)
	 */
	public void setStoreQq(java.lang.String storeQq) {
		set("store_qq", storeQq);
	}

	/**
	 * QQ(作废)
	 */
	public java.lang.String getStoreQq() {
		return getStr("store_qq");
	}

	/**
	 * 商家电话(作废)
	 */
	public void setStorePhone(java.lang.String storePhone) {
		set("store_phone", storePhone);
	}

	/**
	 * 商家电话(作废)
	 */
	public java.lang.String getStorePhone() {
		return getStr("store_phone");
	}

	/**
	 * 主营商品(作废)
	 */
	public void setStoreZy(java.lang.String storeZy) {
		set("store_zy", storeZy);
	}

	/**
	 * 主营商品(作废)
	 */
	public java.lang.String getStoreZy() {
		return getStr("store_zy");
	}

	/**
	 * 店铺二级域名(作废)
	 */
	public void setStoreDomain(java.lang.String storeDomain) {
		set("store_domain", storeDomain);
	}

	/**
	 * 店铺二级域名(作废)
	 */
	public java.lang.String getStoreDomain() {
		return getStr("store_domain");
	}

	/**
	 * 推荐，0为否，1为是，默认为0
	 */
	public void setStoreRecommend(java.lang.Boolean storeRecommend) {
		set("store_recommend", storeRecommend);
	}

	/**
	 * 推荐，0为否，1为是，默认为0
	 */
	public java.lang.Boolean getStoreRecommend() {
		return get("store_recommend");
	}

	/**
	 * 店铺当前主题(作废)
	 */
	public void setStoreTheme(java.lang.String storeTheme) {
		set("store_theme", storeTheme);
	}

	/**
	 * 店铺当前主题(作废)
	 */
	public java.lang.String getStoreTheme() {
		return getStr("store_theme");
	}

	/**
	 * 店铺信用
	 */
	public void setStoreCredit(java.lang.Integer storeCredit) {
		set("store_credit", storeCredit);
	}

	/**
	 * 店铺信用
	 */
	public java.lang.Integer getStoreCredit() {
		return getInt("store_credit");
	}

	/**
	 * 描述相符度分数
	 */
	public void setStoreDesccredit(java.math.BigDecimal storeDesccredit) {
		set("store_desccredit", storeDesccredit);
	}

	/**
	 * 描述相符度分数
	 */
	public java.math.BigDecimal getStoreDesccredit() {
		return get("store_desccredit");
	}

	/**
	 * 服务态度分数
	 */
	public void setStoreServicecredit(java.math.BigDecimal storeServicecredit) {
		set("store_servicecredit", storeServicecredit);
	}

	/**
	 * 服务态度分数
	 */
	public java.math.BigDecimal getStoreServicecredit() {
		return get("store_servicecredit");
	}

	/**
	 * 发货速度分数
	 */
	public void setStoreDeliverycredit(java.math.BigDecimal storeDeliverycredit) {
		set("store_deliverycredit", storeDeliverycredit);
	}

	/**
	 * 发货速度分数
	 */
	public java.math.BigDecimal getStoreDeliverycredit() {
		return get("store_deliverycredit");
	}

	/**
	 * 店铺收藏数量
	 */
	public void setStoreCollect(java.lang.Long storeCollect) {
		set("store_collect", storeCollect);
	}

	/**
	 * 店铺收藏数量
	 */
	public java.lang.Long getStoreCollect() {
		return getLong("store_collect");
	}

	/**
	 * 店铺幻灯片(作废)
	 */
	public void setStoreSlide(java.lang.String storeSlide) {
		set("store_slide", storeSlide);
	}

	/**
	 * 店铺幻灯片(作废)
	 */
	public java.lang.String getStoreSlide() {
		return getStr("store_slide");
	}

	/**
	 * 店铺幻灯片链接(作废)
	 */
	public void setStoreSlideUrl(java.lang.String storeSlideUrl) {
		set("store_slide_url", storeSlideUrl);
	}

	/**
	 * 店铺幻灯片链接(作废)
	 */
	public java.lang.String getStoreSlideUrl() {
		return getStr("store_slide_url");
	}

	/**
	 * 打印订单页面下方说明文字(作废)
	 */
	public void setStorePrintdesc(java.lang.String storePrintdesc) {
		set("store_printdesc", storePrintdesc);
	}

	/**
	 * 打印订单页面下方说明文字(作废)
	 */
	public java.lang.String getStorePrintdesc() {
		return getStr("store_printdesc");
	}

	/**
	 * 店铺销量
	 */
	public void setStoreSales(java.lang.Long storeSales) {
		set("store_sales", storeSales);
	}

	/**
	 * 店铺销量
	 */
	public java.lang.Long getStoreSales() {
		return getLong("store_sales");
	}

	/**
	 * 售前客服(作废)
	 */
	public void setStorePresales(java.lang.String storePresales) {
		set("store_presales", storePresales);
	}

	/**
	 * 售前客服(作废)
	 */
	public java.lang.String getStorePresales() {
		return getStr("store_presales");
	}

	/**
	 * 售后客服(作废)
	 */
	public void setStoreAftersales(java.lang.String storeAftersales) {
		set("store_aftersales", storeAftersales);
	}

	/**
	 * 售后客服(作废)
	 */
	public java.lang.String getStoreAftersales() {
		return getStr("store_aftersales");
	}

	/**
	 * 工作时间(作废)
	 */
	public void setStoreWorkingtime(java.lang.String storeWorkingtime) {
		set("store_workingtime", storeWorkingtime);
	}

	/**
	 * 工作时间(作废)
	 */
	public java.lang.String getStoreWorkingtime() {
		return getStr("store_workingtime");
	}

	/**
	 * 超出该金额免运费，大于0才表示该值有效
	 */
	public void setStoreFreePrice(java.math.BigDecimal storeFreePrice) {
		set("store_free_price", storeFreePrice);
	}

	/**
	 * 超出该金额免运费，大于0才表示该值有效
	 */
	public java.math.BigDecimal getStoreFreePrice() {
		return get("store_free_price");
	}

	/**
	 *  库存预警数(作废)
	 */
	public void setStoreWarningStorage(java.lang.Integer storeWarningStorage) {
		set("store_warning_storage", storeWarningStorage);
	}

	/**
	 *  库存预警数(作废)
	 */
	public java.lang.Integer getStoreWarningStorage() {
		return getInt("store_warning_storage");
	}

	/**
	 * 店铺装修开关(0-关闭 装修编号-开启)（作废）
	 */
	public void setStoreDecorationSwitch(java.lang.Long storeDecorationSwitch) {
		set("store_decoration_switch", storeDecorationSwitch);
	}

	/**
	 * 店铺装修开关(0-关闭 装修编号-开启)（作废）
	 */
	public java.lang.Long getStoreDecorationSwitch() {
		return getLong("store_decoration_switch");
	}

	/**
	 * 开启店铺装修时，仅显示店铺装修(1-是 0-否（作废）
	 */
	public void setStoreDecorationOnly(java.lang.Boolean storeDecorationOnly) {
		set("store_decoration_only", storeDecorationOnly);
	}

	/**
	 * 开启店铺装修时，仅显示店铺装修(1-是 0-否（作废）
	 */
	public java.lang.Boolean getStoreDecorationOnly() {
		return get("store_decoration_only");
	}

	/**
	 * 是否自营店铺 1是 0否（作废）
	 */
	public void setIsOwnShop(java.lang.Integer isOwnShop) {
		set("is_own_shop", isOwnShop);
	}

	/**
	 * 是否自营店铺 1是 0否（作废）
	 */
	public java.lang.Integer getIsOwnShop() {
		return getInt("is_own_shop");
	}

	/**
	 * 自营店是否绑定全部分类 0否1是（作废）
	 */
	public void setBindAllGc(java.lang.Boolean bindAllGc) {
		set("bind_all_gc", bindAllGc);
	}

	/**
	 * 自营店是否绑定全部分类 0否1是（作废）
	 */
	public java.lang.Boolean getBindAllGc() {
		return get("bind_all_gc");
	}

	/**
	 * 7天退换（作废）
	 */
	public void setQitian(java.lang.Boolean qitian) {
		set("qitian", qitian);
	}

	/**
	 * 7天退换（作废）
	 */
	public java.lang.Boolean getQitian() {
		return get("qitian");
	}

	/**
	 * 正品保障（作废）
	 */
	public void setCertified(java.lang.Boolean certified) {
		set("certified", certified);
	}

	/**
	 * 正品保障（作废）
	 */
	public java.lang.Boolean getCertified() {
		return get("certified");
	}

	/**
	 * 退货承诺（作废）
	 */
	public void setReturned(java.lang.Boolean returned) {
		set("returned", returned);
	}

	/**
	 * 退货承诺（作废）
	 */
	public java.lang.Boolean getReturned() {
		return get("returned");
	}

	/**
	 * 商家配送时间（作废）
	 */
	public void setStoreFreeTime(java.lang.String storeFreeTime) {
		set("store_free_time", storeFreeTime);
	}

	/**
	 * 商家配送时间（作废）
	 */
	public java.lang.String getStoreFreeTime() {
		return getStr("store_free_time");
	}

	/**
	 * 手机店铺 轮播图链接地址（作废）
	 */
	public void setMbSlide(java.lang.String mbSlide) {
		set("mb_slide", mbSlide);
	}

	/**
	 * 手机店铺 轮播图链接地址（作废）
	 */
	public java.lang.String getMbSlide() {
		return getStr("mb_slide");
	}

	/**
	 * 手机版广告链接（作废）
	 */
	public void setMbSlideUrl(java.lang.String mbSlideUrl) {
		set("mb_slide_url", mbSlideUrl);
	}

	/**
	 * 手机版广告链接（作废）
	 */
	public java.lang.String getMbSlideUrl() {
		return getStr("mb_slide_url");
	}

	/**
	 * 店铺默认配送区域（作废）
	 */
	public void setDeliverRegion(java.lang.String deliverRegion) {
		set("deliver_region", deliverRegion);
	}

	/**
	 * 店铺默认配送区域（作废）
	 */
	public java.lang.String getDeliverRegion() {
		return getStr("deliver_region");
	}

	/**
	 * 货到付款（作废）
	 */
	public void setCod(java.lang.Boolean cod) {
		set("cod", cod);
	}

	/**
	 * 货到付款（作废）
	 */
	public java.lang.Boolean getCod() {
		return get("cod");
	}

	/**
	 * 两小时发货（作废）
	 */
	public void setTwoHour(java.lang.Boolean twoHour) {
		set("two_hour", twoHour);
	}

	/**
	 * 两小时发货（作废）
	 */
	public java.lang.Boolean getTwoHour() {
		return get("two_hour");
	}

	/**
	 * 保证服务开关（作废）
	 */
	public void setEnsure(java.lang.Boolean ensure) {
		set("ensure", ensure);
	}

	/**
	 * 保证服务开关（作废）
	 */
	public java.lang.Boolean getEnsure() {
		return get("ensure");
	}

	/**
	 * 保证金额（作废）
	 */
	public void setDeposit(java.math.BigDecimal deposit) {
		set("deposit", deposit);
	}

	/**
	 * 保证金额（作废）
	 */
	public java.math.BigDecimal getDeposit() {
		return get("deposit");
	}

	/**
	 * 保证金显示开关（作废）
	 */
	public void setDepositIcon(java.lang.Boolean depositIcon) {
		set("deposit_icon", depositIcon);
	}

	/**
	 * 保证金显示开关（作废）
	 */
	public java.lang.Boolean getDepositIcon() {
		return get("deposit_icon");
	}

	/**
	 * 店铺可用资金（作废）
	 */
	public void setStoreMoney(java.math.BigDecimal storeMoney) {
		set("store_money", storeMoney);
	}

	/**
	 * 店铺可用资金（作废）
	 */
	public java.math.BigDecimal getStoreMoney() {
		return get("store_money");
	}

	/**
	 * 待结算资金（作废）
	 */
	public void setPendingMoney(java.math.BigDecimal pendingMoney) {
		set("pending_money", pendingMoney);
	}

	/**
	 * 待结算资金（作废）
	 */
	public java.math.BigDecimal getPendingMoney() {
		return get("pending_money");
	}

	/**
	 * 未删除0，已删除1（作废）
	 */
	public void setDeleted(java.lang.Boolean deleted) {
		set("deleted", deleted);
	}

	/**
	 * 未删除0，已删除1（作废）
	 */
	public java.lang.Boolean getDeleted() {
		return get("deleted");
	}

	/**
	 * 店铺发布商品是否需要审核
	 */
	public void setGoodsExamine(java.lang.Boolean goodsExamine) {
		set("goods_examine", goodsExamine);
	}

	/**
	 * 店铺发布商品是否需要审核
	 */
	public java.lang.Boolean getGoodsExamine() {
		return get("goods_examine");
	}

	/**
	 * 客户下单, 接收下单提醒短信（作废）
	 */
	public void setServicePhone(java.lang.String servicePhone) {
		set("service_phone", servicePhone);
	}

	/**
	 * 客户下单, 接收下单提醒短信（作废）
	 */
	public java.lang.String getServicePhone() {
		return getStr("service_phone");
	}

	/**
	 * 是否启用二级域名.1:启用;0:关闭（作废）
	 */
	public void setDomainEnable(java.lang.Boolean domainEnable) {
		set("domain_enable", domainEnable);
	}

	/**
	 * 是否启用二级域名.1:启用;0:关闭（作废）
	 */
	public java.lang.Boolean getDomainEnable() {
		return get("domain_enable");
	}

	/**
	 * 主营商品分类ID（作废）
	 */
	public void setMainCategoryId(java.lang.Integer mainCategoryId) {
		set("main_category_id", mainCategoryId);
	}

	/**
	 * 主营商品分类ID（作废）
	 */
	public java.lang.Integer getMainCategoryId() {
		return getInt("main_category_id");
	}

	/**
	 * 平成抽取佣金比例
	 */
	public void setButlerRate(java.math.BigDecimal butlerRate) {
		set("butler_rate", butlerRate);
	}

	/**
	 * 平成抽取佣金比例
	 */
	public java.math.BigDecimal getButlerRate() {
		return get("butler_rate");
	}

	/**
	 * 1 个人店铺 2 企业店铺
	 */
	public void setStoreType(java.lang.Integer storeType) {
		set("store_type", storeType);
	}

	/**
	 * 1 个人店铺 2 企业店铺
	 */
	public java.lang.Integer getStoreType() {
		return getInt("store_type");
	}

	/**
	 * 店铺简介
	 */
	public void setStoreDesc(java.lang.String storeDesc) {
		set("store_desc", storeDesc);
	}

	/**
	 * 店铺简介
	 */
	public java.lang.String getStoreDesc() {
		return getStr("store_desc");
	}

	/**
	 * 身份证正面
	 */
	public void setIdFront(java.lang.String idFront) {
		set("id_front", idFront);
	}

	/**
	 * 身份证正面
	 */
	public java.lang.String getIdFront() {
		return getStr("id_front");
	}

	/**
	 * 身份正反面
	 */
	public void setIdBack(java.lang.String idBack) {
		set("id_back", idBack);
	}

	/**
	 * 身份正反面
	 */
	public java.lang.String getIdBack() {
		return getStr("id_back");
	}

	/**
	 * 手持身份证
	 */
	public void setIdHold(java.lang.String idHold) {
		set("id_hold", idHold);
	}

	/**
	 * 手持身份证
	 */
	public java.lang.String getIdHold() {
		return getStr("id_hold");
	}

	/**
	 * 营业执照照片
	 */
	public void setBusinessLicense(java.lang.String businessLicense) {
		set("business_license", businessLicense);
	}

	/**
	 * 营业执照照片
	 */
	public java.lang.String getBusinessLicense() {
		return getStr("business_license");
	}

	/**
	 * 营业执照编号
	 */
	public void setUnifiedSocialReferenceCode(java.lang.String unifiedSocialReferenceCode) {
		set("unified_social_reference_code", unifiedSocialReferenceCode);
	}

	/**
	 * 营业执照编号
	 */
	public java.lang.String getUnifiedSocialReferenceCode() {
		return getStr("unified_social_reference_code");
	}

	/**
	 * 营业执照有效期类型(1长期有效 2固定期限)
	 */
	public void setValidityPeriodType(java.lang.Integer validityPeriodType) {
		set("validity_period_type", validityPeriodType);
	}

	/**
	 * 营业执照有效期类型(1长期有效 2固定期限)
	 */
	public java.lang.Integer getValidityPeriodType() {
		return getInt("validity_period_type");
	}

	/**
	 * 营业执照开始时间 
	 */
	public void setStartValidityPeriod(java.util.Date startValidityPeriod) {
		set("start_validity_period", startValidityPeriod);
	}

	/**
	 * 营业执照开始时间 
	 */
	public java.util.Date getStartValidityPeriod() {
		return get("start_validity_period");
	}

	/**
	 * 营业执照结束时间
	 */
	public void setEndValidityPeriod(java.util.Date endValidityPeriod) {
		set("end_validity_period", endValidityPeriod);
	}

	/**
	 * 营业执照结束时间
	 */
	public java.util.Date getEndValidityPeriod() {
		return get("end_validity_period");
	}

	/**
	 * 银行卡号
	 */
	public void setCardNum(java.lang.String cardNum) {
		set("card_num", cardNum);
	}

	/**
	 * 银行卡号
	 */
	public java.lang.String getCardNum() {
		return getStr("card_num");
	}

	/**
	 * 银行卡正面
	 */
	public void setCardFront(java.lang.String cardFront) {
		set("card_front", cardFront);
	}

	/**
	 * 银行卡正面
	 */
	public java.lang.String getCardFront() {
		return getStr("card_front");
	}

	/**
	 * 银行卡背面
	 */
	public void setCardBack(java.lang.String cardBack) {
		set("card_back", cardBack);
	}

	/**
	 * 银行卡背面
	 */
	public java.lang.String getCardBack() {
		return getStr("card_back");
	}

}
