package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderDivRate<M extends BaseOrderDivRate<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}

	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 店铺等级
	 */
	public void setStoreLevelName(java.lang.String storeLevelName) {
		set("store_level_name", storeLevelName);
	}

	/**
	 * 店铺等级
	 */
	public java.lang.String getStoreLevelName() {
		return getStr("store_level_name");
	}

	/**
	 * 平台抽成比例
	 */
	public void setButlerCommissionRate(java.math.BigDecimal butlerCommissionRate) {
		set("butler_commission_rate", butlerCommissionRate);
	}

	/**
	 * 平台抽成比例
	 */
	public java.math.BigDecimal getButlerCommissionRate() {
		return get("butler_commission_rate");
	}

	/**
	 * 推广人员ID
	 */
	public void setPromoteUserId(java.lang.Integer promoteUserId) {
		set("promote_user_id", promoteUserId);
	}

	/**
	 * 推广人员ID
	 */
	public java.lang.Integer getPromoteUserId() {
		return getInt("promote_user_id");
	}

	/**
	 * 推广用户等级
	 */
	public void setPromoteUserLevelName(java.lang.String promoteUserLevelName) {
		set("promote_user_level_name", promoteUserLevelName);
	}

	/**
	 * 推广用户等级
	 */
	public java.lang.String getPromoteUserLevelName() {
		return getStr("promote_user_level_name");
	}

	/**
	 * 推广抽成比例
	 */
	public void setPromoteCommissionRate(java.math.BigDecimal promoteCommissionRate) {
		set("promote_commission_rate", promoteCommissionRate);
	}

	/**
	 * 推广抽成比例
	 */
	public java.math.BigDecimal getPromoteCommissionRate() {
		return get("promote_commission_rate");
	}

	/**
	 * 店铺推广金额
	 */
	public void setStorePromote(java.math.BigDecimal storePromote) {
		set("store_promote", storePromote);
	}

	/**
	 * 店铺推广金额
	 */
	public java.math.BigDecimal getStorePromote() {
		return get("store_promote");
	}

	/**
	 * 首单奖励
	 */
	public void setFirstReward(java.math.BigDecimal firstReward) {
		set("first_reward", firstReward);
	}

	/**
	 * 首单奖励
	 */
	public java.math.BigDecimal getFirstReward() {
		return get("first_reward");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
