package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodCollect<M extends BaseGoodCollect<M>> extends BaseModel<M> implements IBean {

	public void setCollectId(java.lang.Integer collectId) {
		set("collect_id", collectId);
	}

	public java.lang.Integer getCollectId() {
		return getInt("collect_id");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 商品id
	 */
	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}

	/**
	 * 商品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	public void setCatId3(java.lang.Integer catId3) {
		set("cat_id3", catId3);
	}

	public java.lang.Integer getCatId3() {
		return getInt("cat_id3");
	}

	/**
	 * 添加时间
	 */
	public void setAddTime(java.lang.Long addTime) {
		set("add_time", addTime);
	}

	/**
	 * 添加时间
	 */
	public java.lang.Long getAddTime() {
		return getLong("add_time");
	}

}
