package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSpec<M extends BaseSpec<M>> extends BaseModel<M> implements IBean {

	/**
	 * 规格表
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 规格表
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 规格名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 规格名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 分类ID
	 */
	public void setCategoryId(java.lang.Integer categoryId) {
		set("categoryId", categoryId);
	}

	/**
	 * 分类ID
	 */
	public java.lang.Integer getCategoryId() {
		return getInt("categoryId");
	}

}
