package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends BaseModel<M> implements IBean {

	/**
	 * 订单id
	 */
	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}

	/**
	 * 订单id
	 */
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 订单编号
	 */
	public void setOrderSn(java.lang.String orderSn) {
		set("order_sn", orderSn);
	}

	/**
	 * 订单编号
	 */
	public java.lang.String getOrderSn() {
		return getStr("order_sn");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 主订单号
	 */
	public void setMasterOrderSn(java.lang.String masterOrderSn) {
		set("master_order_sn", masterOrderSn);
	}

	/**
	 * 主订单号
	 */
	public java.lang.String getMasterOrderSn() {
		return getStr("master_order_sn");
	}

	/**
	 * 订单流程状态.0正常进行中的订单，3取消订单，4完成状态，5退款订单-有点类似于订单类型，标识订单处于哪个流程中
	 */
	public void setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
	}

	/**
	 * 订单流程状态.0正常进行中的订单，3取消订单，4完成状态，5退款订单-有点类似于订单类型，标识订单处于哪个流程中
	 */
	public java.lang.Integer getOrderStatus() {
		return getInt("order_status");
	}

	/**
	 * 支付状态.0待支付，1已支付，2部分支付，3已退款，4拒绝退款 -支付流程中的订单状态流转
	 */
	public void setPayStatus(java.lang.Integer payStatus) {
		set("pay_status", payStatus);
	}

	/**
	 * 支付状态.0待支付，1已支付，2部分支付，3已退款，4拒绝退款 -支付流程中的订单状态流转
	 */
	public java.lang.Integer getPayStatus() {
		return getInt("pay_status");
	}

	/**
	 * 发货状态0未发货 1已发货 2已收货 -发货流程中订单流转状态
	 */
	public void setShippingStatus(java.lang.Integer shippingStatus) {
		set("shipping_status", shippingStatus);
	}

	/**
	 * 发货状态0未发货 1已发货 2已收货 -发货流程中订单流转状态
	 */
	public java.lang.Integer getShippingStatus() {
		return getInt("shipping_status");
	}

	/**
	 * 是否评价（0：未评价；1：已评价）
	 */
	public void setIsComment(java.lang.Integer isComment) {
		set("is_comment", isComment);
	}

	/**
	 * 是否评价（0：未评价；1：已评价）
	 */
	public java.lang.Integer getIsComment() {
		return getInt("is_comment");
	}

	/**
	 * 收货人
	 */
	public void setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
	}

	/**
	 * 收货人
	 */
	public java.lang.String getConsignee() {
		return getStr("consignee");
	}

	/**
	 * 国家
	 */
	public void setCountry(java.lang.Integer country) {
		set("country", country);
	}

	/**
	 * 国家
	 */
	public java.lang.Integer getCountry() {
		return getInt("country");
	}

	/**
	 * 省份
	 */
	public void setProvince(java.lang.Integer province) {
		set("province", province);
	}

	/**
	 * 省份
	 */
	public java.lang.Integer getProvince() {
		return getInt("province");
	}

	/**
	 * 城市
	 */
	public void setCity(java.lang.Integer city) {
		set("city", city);
	}

	/**
	 * 城市
	 */
	public java.lang.Integer getCity() {
		return getInt("city");
	}

	/**
	 * 县区
	 */
	public void setDistrict(java.lang.Integer district) {
		set("district", district);
	}

	/**
	 * 县区
	 */
	public java.lang.Integer getDistrict() {
		return getInt("district");
	}

	/**
	 * 乡镇
	 */
	public void setTwon(java.lang.Integer twon) {
		set("twon", twon);
	}

	/**
	 * 乡镇
	 */
	public java.lang.Integer getTwon() {
		return getInt("twon");
	}

	/**
	 * 地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	/**
	 * 地址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 邮政编码
	 */
	public void setZipcode(java.lang.String zipcode) {
		set("zipcode", zipcode);
	}

	/**
	 * 邮政编码
	 */
	public java.lang.String getZipcode() {
		return getStr("zipcode");
	}

	/**
	 * 手机
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	/**
	 * 手机
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * 邮件
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	/**
	 * 邮件
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}

	/**
	 * 物流单号
	 */
	public void setShippingCode(java.lang.String shippingCode) {
		set("shipping_code", shippingCode);
	}

	/**
	 * 物流单号
	 */
	public java.lang.String getShippingCode() {
		return getStr("shipping_code");
	}

	/**
	 * 物流名称(物流公司ID)
	 */
	public void setShippingName(java.lang.String shippingName) {
		set("shipping_name", shippingName);
	}

	/**
	 * 物流名称(物流公司ID)
	 */
	public java.lang.String getShippingName() {
		return getStr("shipping_name");
	}

	/**
	 * 邮费
	 */
	public void setShippingPrice(java.math.BigDecimal shippingPrice) {
		set("shipping_price", shippingPrice);
	}

	/**
	 * 邮费
	 */
	public java.math.BigDecimal getShippingPrice() {
		return get("shipping_price");
	}

	/**
	 * 最新发货时间
	 */
	public void setShippingTime(java.lang.Long shippingTime) {
		set("shipping_time", shippingTime);
	}

	/**
	 * 最新发货时间
	 */
	public java.lang.Long getShippingTime() {
		return getLong("shipping_time");
	}

	/**
	 * 支付方式 1支付宝支付2微信支付
	 */
	public void setPayCode(java.lang.String payCode) {
		set("pay_code", payCode);
	}

	/**
	 * 支付方式 1支付宝支付2微信支付
	 */
	public java.lang.String getPayCode() {
		return getStr("pay_code");
	}

	/**
	 * 支付方式名称
	 */
	public void setPayName(java.lang.String payName) {
		set("pay_name", payName);
	}

	/**
	 * 支付方式名称
	 */
	public java.lang.String getPayName() {
		return getStr("pay_name");
	}

	/**
	 * 第三方平台交易流水号
	 */
	public void setTransactionId(java.lang.String transactionId) {
		set("transaction_id", transactionId);
	}

	/**
	 * 第三方平台交易流水号
	 */
	public java.lang.String getTransactionId() {
		return getStr("transaction_id");
	}

	/**
	 * 应付款金额
	 */
	public void setOrderAmount(java.math.BigDecimal orderAmount) {
		set("order_amount", orderAmount);
	}

	/**
	 * 应付款金额
	 */
	public java.math.BigDecimal getOrderAmount() {
		return get("order_amount");
	}

	/**
	 * 订单总价
	 */
	public void setTotalAmount(java.math.BigDecimal totalAmount) {
		set("total_amount", totalAmount);
	}

	/**
	 * 订单总价
	 */
	public java.math.BigDecimal getTotalAmount() {
		return get("total_amount");
	}

	/**
	 * 积分抵扣金额
	 */
	public void setPointAsMoney(java.math.BigDecimal pointAsMoney) {
		set("point_as_money", pointAsMoney);
	}

	/**
	 * 积分抵扣金额
	 */
	public java.math.BigDecimal getPointAsMoney() {
		return get("point_as_money");
	}

	/**
	 * 店铺ID
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 店铺ID
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 下单时间
	 */
	public void setAddTime(java.lang.Long addTime) {
		set("add_time", addTime);
	}

	/**
	 * 下单时间
	 */
	public java.lang.Long getAddTime() {
		return getLong("add_time");
	}

	/**
	 * 收货确认时间
	 */
	public void setConfirmTime(java.lang.Integer confirmTime) {
		set("confirm_time", confirmTime);
	}

	/**
	 * 收货确认时间
	 */
	public java.lang.Integer getConfirmTime() {
		return getInt("confirm_time");
	}

	/**
	 * 支付时间
	 */
	public void setPayTime(java.lang.Long payTime) {
		set("pay_time", payTime);
	}

	/**
	 * 支付时间
	 */
	public java.lang.Long getPayTime() {
		return getLong("pay_time");
	}

	/**
	 * 取消时间
	 */
	public void setCancelTime(java.util.Date cancelTime) {
		set("cancel_time", cancelTime);
	}

	/**
	 * 取消时间
	 */
	public java.util.Date getCancelTime() {
		return get("cancel_time");
	}

	/**
	 * 2：未提醒发货 3：提醒发货
	 */
	public void setRemind(java.lang.Integer remind) {
		set("remind", remind);
	}

	/**
	 * 2：未提醒发货 3：提醒发货
	 */
	public java.lang.Integer getRemind() {
		return getInt("remind");
	}

	/**
	 * 活动类型：1 普通订单、2 秒杀活动订单、3 一元抢购抽奖订单
	 */
	public void setActivityType(java.lang.Integer activityType) {
		set("activity_type", activityType);
	}

	/**
	 * 活动类型：1 普通订单、2 秒杀活动订单、3 一元抢购抽奖订单
	 */
	public java.lang.Integer getActivityType() {
		return getInt("activity_type");
	}

	/**
	 * 用户备注
	 */
	public void setUserNote(java.lang.String userNote) {
		set("user_note", userNote);
	}

	/**
	 * 用户备注
	 */
	public java.lang.String getUserNote() {
		return getStr("user_note");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreatedBy(java.lang.String createdBy) {
		set("created_by", createdBy);
	}

	public java.lang.String getCreatedBy() {
		return getStr("created_by");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

}
