package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCart<M extends BaseCart<M>> extends BaseModel<M> implements IBean {

	/**
	 * 购物车信息ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 购物车信息ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * session
	 */
	public void setSessionId(java.lang.String sessionId) {
		set("session_id", sessionId);
	}

	/**
	 * session
	 */
	public java.lang.String getSessionId() {
		return getStr("session_id");
	}

	/**
	 * 规格ID
	 */
	public void setItemId(java.lang.Integer itemId) {
		set("item_id", itemId);
	}

	/**
	 * 规格ID
	 */
	public java.lang.Integer getItemId() {
		return getInt("item_id");
	}

	/**
	 * 商品id
	 */
	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}

	/**
	 * 商品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 商品货号
	 */
	public void setGoodsSn(java.lang.String goodsSn) {
		set("goods_sn", goodsSn);
	}

	/**
	 * 商品货号
	 */
	public java.lang.String getGoodsSn() {
		return getStr("goods_sn");
	}

	/**
	 * 商品名称
	 */
	public void setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
	}

	/**
	 * 商品名称
	 */
	public java.lang.String getGoodsName() {
		return getStr("goods_name");
	}

	/**
	 * 购买数量
	 */
	public void setGoodsNum(java.lang.Integer goodsNum) {
		set("goods_num", goodsNum);
	}

	/**
	 * 购买数量
	 */
	public java.lang.Integer getGoodsNum() {
		return getInt("goods_num");
	}

	/**
	 * 商品规格key 对应butler_spec_goods_price 表
	 */
	public void setSpecKey(java.lang.String specKey) {
		set("spec_key", specKey);
	}

	/**
	 * 商品规格key 对应butler_spec_goods_price 表
	 */
	public java.lang.String getSpecKey() {
		return getStr("spec_key");
	}

	/**
	 * 商品规格组合名称
	 */
	public void setSpecKeyName(java.lang.String specKeyName) {
		set("spec_key_name", specKeyName);
	}

	/**
	 * 商品规格组合名称
	 */
	public java.lang.String getSpecKeyName() {
		return getStr("spec_key_name");
	}

	/**
	 * 加入购物车的时间
	 */
	public void setAddTime(java.lang.Integer addTime) {
		set("add_time", addTime);
	}

	/**
	 * 加入购物车的时间
	 */
	public java.lang.Integer getAddTime() {
		return getInt("add_time");
	}

	/**
	 * 商家店铺ID
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 商家店铺ID
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

}
