package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCouponPosition<M extends BaseCouponPosition<M>> extends BaseModel<M> implements IBean {

	/**
	 * 自增长ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增长ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 优惠券活动ID
	 */
	public void setActivityId(java.lang.Integer activityId) {
		set("activity_id", activityId);
	}

	/**
	 * 优惠券活动ID
	 */
	public java.lang.Integer getActivityId() {
		return getInt("activity_id");
	}

	/**
	 * 显示类型 1：平台广告区域、2：店铺首页、3：商品详情页、4:：朋友圈、5：二维码、6：购物车
	 */
	public void setShowType(java.lang.Integer showType) {
		set("show_type", showType);
	}

	/**
	 * 显示类型 1：平台广告区域、2：店铺首页、3：商品详情页、4:：朋友圈、5：二维码、6：购物车
	 */
	public java.lang.Integer getShowType() {
		return getInt("show_type");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
