package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStoreApply<M extends BaseStoreApply<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 申请人会员ID
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	/**
	 * 申请人会员ID
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 代理商角色ID 
	 */
	public void setAgentRoleId(java.lang.Integer agentRoleId) {
		set("agent_role_id", agentRoleId);
	}

	/**
	 * 代理商角色ID 
	 */
	public java.lang.Integer getAgentRoleId() {
		return getInt("agent_role_id");
	}

	/**
	 * 是否为虚拟供应商 0否 1是 （agent_role_id = 4时有效）
	 */
	public void setIsFictitiousSupplier(java.lang.Integer isFictitiousSupplier) {
		set("is_fictitious_supplier", isFictitiousSupplier);
	}

	/**
	 * 是否为虚拟供应商 0否 1是 （agent_role_id = 4时有效）
	 */
	public java.lang.Integer getIsFictitiousSupplier() {
		return getInt("is_fictitious_supplier");
	}

	/**
	 * 代理商代理省
	 */
	public void setAgentProvinceId(java.lang.Integer agentProvinceId) {
		set("agent_province_id", agentProvinceId);
	}

	/**
	 * 代理商代理省
	 */
	public java.lang.Integer getAgentProvinceId() {
		return getInt("agent_province_id");
	}

	/**
	 * 代理商代理市
	 */
	public void setAgentCityId(java.lang.Integer agentCityId) {
		set("agent_city_id", agentCityId);
	}

	/**
	 * 代理商代理市
	 */
	public java.lang.Integer getAgentCityId() {
		return getInt("agent_city_id");
	}

	/**
	 * 代理商代理区
	 */
	public void setAgentDistrictId(java.lang.Integer agentDistrictId) {
		set("agent_district_id", agentDistrictId);
	}

	/**
	 * 代理商代理区
	 */
	public java.lang.Integer getAgentDistrictId() {
		return getInt("agent_district_id");
	}

	/**
	 * 联系人姓名
	 */
	public void setContactsName(java.lang.String contactsName) {
		set("contacts_name", contactsName);
	}

	/**
	 * 联系人姓名
	 */
	public java.lang.String getContactsName() {
		return getStr("contacts_name");
	}

	/**
	 * 联系人手机
	 */
	public void setContactsMobile(java.lang.String contactsMobile) {
		set("contacts_mobile", contactsMobile);
	}

	/**
	 * 联系人手机
	 */
	public java.lang.String getContactsMobile() {
		return getStr("contacts_mobile");
	}

	/**
	 * 联系人邮箱
	 */
	public void setContactsEmail(java.lang.String contactsEmail) {
		set("contacts_email", contactsEmail);
	}

	/**
	 * 联系人邮箱
	 */
	public java.lang.String getContactsEmail() {
		return getStr("contacts_email");
	}

	/**
	 * 联系人所在地址
	 */
	public void setContactsAddress(java.lang.String contactsAddress) {
		set("contacts_address", contactsAddress);
	}

	/**
	 * 联系人所在地址
	 */
	public java.lang.String getContactsAddress() {
		return getStr("contacts_address");
	}

	/**
	 * 公司名称
	 */
	public void setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
	}

	/**
	 * 公司名称
	 */
	public java.lang.String getCompanyName() {
		return getStr("company_name");
	}

	/**
	 * 公司性质
	 */
	public void setCompanyType(java.lang.Boolean companyType) {
		set("company_type", companyType);
	}

	/**
	 * 公司性质
	 */
	public java.lang.Boolean getCompanyType() {
		return get("company_type");
	}

	/**
	 * 公司网址
	 */
	public void setCompanyWebsite(java.lang.String companyWebsite) {
		set("company_website", companyWebsite);
	}

	/**
	 * 公司网址
	 */
	public java.lang.String getCompanyWebsite() {
		return getStr("company_website");
	}

	/**
	 * 公司所在省份
	 */
	public void setCompanyProvince(java.lang.Integer companyProvince) {
		set("company_province", companyProvince);
	}

	/**
	 * 公司所在省份
	 */
	public java.lang.Integer getCompanyProvince() {
		return getInt("company_province");
	}

	/**
	 * 公司所在城市
	 */
	public void setCompanyCity(java.lang.Integer companyCity) {
		set("company_city", companyCity);
	}

	/**
	 * 公司所在城市
	 */
	public java.lang.Integer getCompanyCity() {
		return getInt("company_city");
	}

	/**
	 * 公司所在地区
	 */
	public void setCompanyDistrict(java.lang.Integer companyDistrict) {
		set("company_district", companyDistrict);
	}

	/**
	 * 公司所在地区
	 */
	public java.lang.Integer getCompanyDistrict() {
		return getInt("company_district");
	}

	/**
	 * 公司详细地址
	 */
	public void setCompanyAddress(java.lang.String companyAddress) {
		set("company_address", companyAddress);
	}

	/**
	 * 公司详细地址
	 */
	public java.lang.String getCompanyAddress() {
		return getStr("company_address");
	}

	/**
	 * 固定电话
	 */
	public void setCompanyTelephone(java.lang.String companyTelephone) {
		set("company_telephone", companyTelephone);
	}

	/**
	 * 固定电话
	 */
	public java.lang.String getCompanyTelephone() {
		return getStr("company_telephone");
	}

	/**
	 * 电子邮箱
	 */
	public void setCompanyEmail(java.lang.String companyEmail) {
		set("company_email", companyEmail);
	}

	/**
	 * 电子邮箱
	 */
	public java.lang.String getCompanyEmail() {
		return getStr("company_email");
	}

	/**
	 * 传真
	 */
	public void setCompanyFax(java.lang.String companyFax) {
		set("company_fax", companyFax);
	}

	/**
	 * 传真
	 */
	public java.lang.String getCompanyFax() {
		return getStr("company_fax");
	}

	/**
	 * 邮政编码
	 */
	public void setCompanyZipcode(java.lang.String companyZipcode) {
		set("company_zipcode", companyZipcode);
	}

	/**
	 * 邮政编码
	 */
	public java.lang.String getCompanyZipcode() {
		return getStr("company_zipcode");
	}

	/**
	 * 营业执照注册号/统一社会信用代码
	 */
	public void setBusinessLicenceNumber(java.lang.String businessLicenceNumber) {
		set("business_licence_number", businessLicenceNumber);
	}

	/**
	 * 营业执照注册号/统一社会信用代码
	 */
	public java.lang.String getBusinessLicenceNumber() {
		return getStr("business_licence_number");
	}

	/**
	 * 营业执照电子版
	 */
	public void setBusinessLicenceCert(java.lang.String businessLicenceCert) {
		set("business_licence_cert", businessLicenceCert);
	}

	/**
	 * 营业执照电子版
	 */
	public java.lang.String getBusinessLicenceCert() {
		return getStr("business_licence_cert");
	}

	/**
	 * 是否为一证一码商家
	 */
	public void setThreeinone(java.lang.Boolean threeinone) {
		set("threeinone", threeinone);
	}

	/**
	 * 是否为一证一码商家
	 */
	public java.lang.Boolean getThreeinone() {
		return get("threeinone");
	}

	/**
	 * 注册资金
	 */
	public void setRegCapital(java.lang.String regCapital) {
		set("reg_capital", regCapital);
	}

	/**
	 * 注册资金
	 */
	public java.lang.String getRegCapital() {
		return getStr("reg_capital");
	}

	/**
	 * 法人代表
	 */
	public void setLegalPerson(java.lang.String legalPerson) {
		set("legal_person", legalPerson);
	}

	/**
	 * 法人代表
	 */
	public java.lang.String getLegalPerson() {
		return getStr("legal_person");
	}

	/**
	 * 法人身份证照片
	 */
	public void setLegalIdentityCert(java.lang.String legalIdentityCert) {
		set("legal_identity_cert", legalIdentityCert);
	}

	/**
	 * 法人身份证照片
	 */
	public java.lang.String getLegalIdentityCert() {
		return getStr("legal_identity_cert");
	}

	/**
	 * 法人身份证号
	 */
	public void setLegalIdentity(java.lang.String legalIdentity) {
		set("legal_identity", legalIdentity);
	}

	/**
	 * 法人身份证号
	 */
	public java.lang.String getLegalIdentity() {
		return getStr("legal_identity");
	}

	/**
	 * 授权书图片
	 */
	public void setPowerAttorneyCert(java.lang.String powerAttorneyCert) {
		set("power_attorney_cert", powerAttorneyCert);
	}

	/**
	 * 授权书图片
	 */
	public java.lang.String getPowerAttorneyCert() {
		return getStr("power_attorney_cert");
	}

	/**
	 * 营业执照有效期
	 */
	public void setBusinessDateStart(java.lang.String businessDateStart) {
		set("business_date_start", businessDateStart);
	}

	/**
	 * 营业执照有效期
	 */
	public java.lang.String getBusinessDateStart() {
		return getStr("business_date_start");
	}

	public void setBusinessDateEnd(java.lang.String businessDateEnd) {
		set("business_date_end", businessDateEnd);
	}

	public java.lang.String getBusinessDateEnd() {
		return getStr("business_date_end");
	}

	/**
	 * 组织机构代码
	 */
	public void setOrgnizationCode(java.lang.String orgnizationCode) {
		set("orgnization_code", orgnizationCode);
	}

	/**
	 * 组织机构代码
	 */
	public java.lang.String getOrgnizationCode() {
		return getStr("orgnization_code");
	}

	/**
	 * 组织机构代码证
	 */
	public void setOrgnizationCert(java.lang.String orgnizationCert) {
		set("orgnization_cert", orgnizationCert);
	}

	/**
	 * 组织机构代码证
	 */
	public java.lang.String getOrgnizationCert() {
		return getStr("orgnization_cert");
	}

	/**
	 * 纳税人识别号
	 */
	public void setAttachedTaxNumber(java.lang.String attachedTaxNumber) {
		set("attached_tax_number", attachedTaxNumber);
	}

	/**
	 * 纳税人识别号
	 */
	public java.lang.String getAttachedTaxNumber() {
		return getStr("attached_tax_number");
	}

	/**
	 * 纳税类型税码
	 */
	public void setTaxRate(java.lang.Integer taxRate) {
		set("tax_rate", taxRate);
	}

	/**
	 * 纳税类型税码
	 */
	public java.lang.Integer getTaxRate() {
		return getInt("tax_rate");
	}

	/**
	 * 纳税人类型
	 */
	public void setTaxpayer(java.lang.Boolean taxpayer) {
		set("taxpayer", taxpayer);
	}

	/**
	 * 纳税人类型
	 */
	public java.lang.Boolean getTaxpayer() {
		return get("taxpayer");
	}

	/**
	 * 一般纳税人资格证书
	 */
	public void setTaxpayerCert(java.lang.String taxpayerCert) {
		set("taxpayer_cert", taxpayerCert);
	}

	/**
	 * 一般纳税人资格证书
	 */
	public java.lang.String getTaxpayerCert() {
		return getStr("taxpayer_cert");
	}

	/**
	 * 营业执照经营范围
	 */
	public void setBusinessScope(java.lang.String businessScope) {
		set("business_scope", businessScope);
	}

	/**
	 * 营业执照经营范围
	 */
	public java.lang.String getBusinessScope() {
		return getStr("business_scope");
	}

	/**
	 * 店铺名称
	 */
	public void setStoreName(java.lang.String storeName) {
		set("store_name", storeName);
	}

	/**
	 * 店铺名称
	 */
	public java.lang.String getStoreName() {
		return getStr("store_name");
	}

	/**
	 * 卖家账号
	 */
	public void setSellerName(java.lang.String sellerName) {
		set("seller_name", sellerName);
	}

	/**
	 * 卖家账号
	 */
	public java.lang.String getSellerName() {
		return getStr("seller_name");
	}

	/**
	 * 店铺性质
	 */
	public void setStoreType(java.lang.Boolean storeType) {
		set("store_type", storeType);
	}

	/**
	 * 店铺性质
	 */
	public java.lang.Boolean getStoreType() {
		return get("store_type");
	}

	public void setStoreAddress(java.lang.String storeAddress) {
		set("store_address", storeAddress);
	}

	public java.lang.String getStoreAddress() {
		return getStr("store_address");
	}

	/**
	 * 店铺负责人姓名
	 */
	public void setStorePersonName(java.lang.String storePersonName) {
		set("store_person_name", storePersonName);
	}

	/**
	 * 店铺负责人姓名
	 */
	public java.lang.String getStorePersonName() {
		return getStr("store_person_name");
	}

	/**
	 * 店铺负责人手机
	 */
	public void setStorePersonMobile(java.lang.String storePersonMobile) {
		set("store_person_mobile", storePersonMobile);
	}

	/**
	 * 店铺负责人手机
	 */
	public java.lang.String getStorePersonMobile() {
		return getStr("store_person_mobile");
	}

	/**
	 * 店铺联系人QQ
	 */
	public void setStorePersonQq(java.lang.String storePersonQq) {
		set("store_person_qq", storePersonQq);
	}

	/**
	 * 店铺联系人QQ
	 */
	public java.lang.String getStorePersonQq() {
		return getStr("store_person_qq");
	}

	/**
	 * 店铺负责人邮箱
	 */
	public void setStorePersonEmail(java.lang.String storePersonEmail) {
		set("store_person_email", storePersonEmail);
	}

	/**
	 * 店铺负责人邮箱
	 */
	public java.lang.String getStorePersonEmail() {
		return getStr("store_person_email");
	}

	/**
	 * 店铺负责人身份证照片
	 */
	public void setStorePersonCert(java.lang.String storePersonCert) {
		set("store_person_cert", storePersonCert);
	}

	/**
	 * 店铺负责人身份证照片
	 */
	public java.lang.String getStorePersonCert() {
		return getStr("store_person_cert");
	}

	/**
	 * 店铺负责人身份证照片反面
	 */
	public void setStorePersonCertBack(java.lang.String storePersonCertBack) {
		set("store_person_cert_back", storePersonCertBack);
	}

	/**
	 * 店铺负责人身份证照片反面
	 */
	public java.lang.String getStorePersonCertBack() {
		return getStr("store_person_cert_back");
	}

	/**
	 * 店铺负责人身份证号
	 */
	public void setStorePersonIdentity(java.lang.String storePersonIdentity) {
		set("store_person_identity", storePersonIdentity);
	}

	/**
	 * 店铺负责人身份证号
	 */
	public java.lang.String getStorePersonIdentity() {
		return getStr("store_person_identity");
	}

	/**
	 * 结算银行名称
	 */
	public void setBankAccountName(java.lang.String bankAccountName) {
		set("bank_account_name", bankAccountName);
	}

	/**
	 * 结算银行名称
	 */
	public java.lang.String getBankAccountName() {
		return getStr("bank_account_name");
	}

	/**
	 * 结算银行账号
	 */
	public void setBankAccountNumber(java.lang.String bankAccountNumber) {
		set("bank_account_number", bankAccountNumber);
	}

	/**
	 * 结算银行账号
	 */
	public java.lang.String getBankAccountNumber() {
		return getStr("bank_account_number");
	}

	/**
	 * 开户银行支行名称
	 */
	public void setBankBranchName(java.lang.String bankBranchName) {
		set("bank_branch_name", bankBranchName);
	}

	/**
	 * 开户银行支行名称
	 */
	public java.lang.String getBankBranchName() {
		return getStr("bank_branch_name");
	}

	/**
	 * 银行卡正面照片
	 */
	public void setBankCardCert(java.lang.String bankCardCert) {
		set("bank_card_cert", bankCardCert);
	}

	/**
	 * 银行卡正面照片
	 */
	public java.lang.String getBankCardCert() {
		return getStr("bank_card_cert");
	}

	/**
	 * 开户银行支行所在地
	 */
	public void setBankProvince(java.lang.Integer bankProvince) {
		set("bank_province", bankProvince);
	}

	/**
	 * 开户银行支行所在地
	 */
	public java.lang.Integer getBankProvince() {
		return getInt("bank_province");
	}

	/**
	 * 开户银行支行所在城市
	 */
	public void setBankCity(java.lang.Integer bankCity) {
		set("bank_city", bankCity);
	}

	/**
	 * 开户银行支行所在城市
	 */
	public java.lang.Integer getBankCity() {
		return getInt("bank_city");
	}

	/**
	 * 近一年主营渠道
	 */
	public void setMainChannel(java.lang.Boolean mainChannel) {
		set("main_channel", mainChannel);
	}

	/**
	 * 近一年主营渠道
	 */
	public java.lang.Boolean getMainChannel() {
		return get("main_channel");
	}

	/**
	 * 近一年销售额
	 */
	public void setSalesVolume(java.lang.String salesVolume) {
		set("sales_volume", salesVolume);
	}

	/**
	 * 近一年销售额
	 */
	public java.lang.String getSalesVolume() {
		return getStr("sales_volume");
	}

	/**
	 * 可网售商品数量
	 */
	public void setSkuNum(java.lang.Integer skuNum) {
		set("sku_num", skuNum);
	}

	/**
	 * 可网售商品数量
	 */
	public java.lang.Integer getSkuNum() {
		return getInt("sku_num");
	}

	/**
	 * 同类电子商务网站经验
	 */
	public void setEcExperience(java.lang.Boolean ecExperience) {
		set("ec_experience", ecExperience);
	}

	/**
	 * 同类电子商务网站经验
	 */
	public java.lang.Boolean getEcExperience() {
		return get("ec_experience");
	}

	/**
	 * 预计平均客单价
	 */
	public void setAvgPrice(java.math.BigDecimal avgPrice) {
		set("avg_price", avgPrice);
	}

	/**
	 * 预计平均客单价
	 */
	public java.math.BigDecimal getAvgPrice() {
		return get("avg_price");
	}

	/**
	 * 仓库情况
	 */
	public void setWareHouse(java.lang.Boolean wareHouse) {
		set("ware_house", wareHouse);
	}

	/**
	 * 仓库情况
	 */
	public java.lang.Boolean getWareHouse() {
		return get("ware_house");
	}

	/**
	 * 有无实体店
	 */
	public void setEntityShop(java.lang.Boolean entityShop) {
		set("entity_shop", entityShop);
	}

	/**
	 * 有无实体店
	 */
	public java.lang.Boolean getEntityShop() {
		return get("entity_shop");
	}

	/**
	 * 店铺分类名称
	 */
	public void setScName(java.lang.String scName) {
		set("sc_name", scName);
	}

	/**
	 * 店铺分类名称
	 */
	public java.lang.String getScName() {
		return getStr("sc_name");
	}

	/**
	 * 店铺分类编号
	 */
	public void setScId(java.lang.Integer scId) {
		set("sc_id", scId);
	}

	/**
	 * 店铺分类编号
	 */
	public java.lang.Integer getScId() {
		return getInt("sc_id");
	}

	/**
	 * 店铺分类保证金
	 */
	public void setScBail(java.lang.Integer scBail) {
		set("sc_bail", scBail);
	}

	/**
	 * 店铺分类保证金
	 */
	public java.lang.Integer getScBail() {
		return getInt("sc_bail");
	}

	/**
	 * 店铺等级编号
	 */
	public void setSgId(java.lang.Integer sgId) {
		set("sg_id", sgId);
	}

	/**
	 * 店铺等级编号
	 */
	public java.lang.Integer getSgId() {
		return getInt("sg_id");
	}

	/**
	 * 店铺等级名称
	 */
	public void setSgName(java.lang.String sgName) {
		set("sg_name", sgName);
	}

	/**
	 * 店铺等级名称
	 */
	public java.lang.String getSgName() {
		return getStr("sg_name");
	}

	/**
	 * 申请分类佣金信息
	 */
	public void setStoreClassIds(java.lang.String storeClassIds) {
		set("store_class_ids", storeClassIds);
	}

	/**
	 * 申请分类佣金信息
	 */
	public java.lang.String getStoreClassIds() {
		return getStr("store_class_ids");
	}

	/**
	 * 付款金额
	 */
	public void setPayingAmount(java.math.BigDecimal payingAmount) {
		set("paying_amount", payingAmount);
	}

	/**
	 * 付款金额
	 */
	public java.math.BigDecimal getPayingAmount() {
		return get("paying_amount");
	}

	/**
	 * 付款凭证
	 */
	public void setPayingAmountCert(java.lang.String payingAmountCert) {
		set("paying_amount_cert", payingAmountCert);
	}

	/**
	 * 付款凭证
	 */
	public java.lang.String getPayingAmountCert() {
		return getStr("paying_amount_cert");
	}

	/**
	 * 审核管理员ID
	 */
	public void setAuditingAdminId(java.lang.Integer auditingAdminId) {
		set("auditing_admin_id", auditingAdminId);
	}

	/**
	 * 审核管理员ID
	 */
	public java.lang.Integer getAuditingAdminId() {
		return getInt("auditing_admin_id");
	}

	/**
	 * 店铺申请状态 0未审核，1通过，2拒绝
	 */
	public void setApplyState(java.lang.Integer applyState) {
		set("apply_state", applyState);
	}

	/**
	 * 店铺申请状态 0未审核，1通过，2拒绝
	 */
	public java.lang.Integer getApplyState() {
		return getInt("apply_state");
	}

	/**
	 * 管理员审核信息
	 */
	public void setReviewMsg(java.lang.String reviewMsg) {
		set("review_msg", reviewMsg);
	}

	/**
	 * 管理员审核信息
	 */
	public java.lang.String getReviewMsg() {
		return getStr("review_msg");
	}

	/**
	 * 提交申请时间
	 */
	public void setAddTime(java.lang.Integer addTime) {
		set("add_time", addTime);
	}

	/**
	 * 提交申请时间
	 */
	public java.lang.Integer getAddTime() {
		return getInt("add_time");
	}

	/**
	 * 申请类型默认0企业1个人
	 */
	public void setApplyType(java.lang.Boolean applyType) {
		set("apply_type", applyType);
	}

	/**
	 * 申请类型默认0企业1个人
	 */
	public java.lang.Boolean getApplyType() {
		return get("apply_type");
	}

	/**
	 * 提成结算时间
	 */
	public void setBonusBalanceTime(java.lang.String bonusBalanceTime) {
		set("bonus_balance_time", bonusBalanceTime);
	}

	/**
	 * 提成结算时间
	 */
	public java.lang.String getBonusBalanceTime() {
		return getStr("bonus_balance_time");
	}

	/**
	 * 工资结算时间
	 */
	public void setWagesBalanceTime(java.lang.String wagesBalanceTime) {
		set("wages_balance_time", wagesBalanceTime);
	}

	/**
	 * 工资结算时间
	 */
	public java.lang.String getWagesBalanceTime() {
		return getStr("wages_balance_time");
	}

	/**
	 * 店铺结算时间
	 */
	public void setStoreBalanceTime(java.lang.String storeBalanceTime) {
		set("store_balance_time", storeBalanceTime);
	}

	/**
	 * 店铺结算时间
	 */
	public java.lang.String getStoreBalanceTime() {
		return getStr("store_balance_time");
	}

}
