package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSpecItem<M extends BaseSpecItem<M>> extends BaseModel<M> implements IBean {

	/**
	 * 规格项id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 规格项id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 规格id
	 */
	public void setSpecId(java.lang.Integer specId) {
		set("spec_id", specId);
	}

	/**
	 * 规格id
	 */
	public java.lang.Integer getSpecId() {
		return getInt("spec_id");
	}

	/**
	 * 规格项
	 */
	public void setItem(java.lang.String item) {
		set("item", item);
	}

	/**
	 * 规格项
	 */
	public java.lang.String getItem() {
		return getStr("item");
	}

	/**
	 * 商家id（作废）
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 商家id（作废）
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

}
