package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLottery<M extends BaseLottery<M>> extends BaseModel<M> implements IBean {

	/**
	 * 自增长id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增长id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 一元抢购抽奖活动标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	/**
	 * 一元抢购抽奖活动标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 一元抢购抽奖活动开始时间
	 */
	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}

	/**
	 * 一元抢购抽奖活动开始时间
	 */
	public java.util.Date getStartTime() {
		return get("start_time");
	}

	/**
	 * 一元抢购抽奖活动结束时间
	 */
	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	/**
	 * 一元抢购抽奖活动结束时间
	 */
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	/**
	 * 参团最大人数限制
	 */
	public void setMaxNum(java.lang.Integer maxNum) {
		set("max_num", maxNum);
	}

	/**
	 * 参团最大人数限制
	 */
	public java.lang.Integer getMaxNum() {
		return getInt("max_num");
	}

	/**
	 * 开团最少人数底限
	 */
	public void setMinNum(java.lang.Integer minNum) {
		set("min_num", minNum);
	}

	/**
	 * 开团最少人数底限
	 */
	public java.lang.Integer getMinNum() {
		return getInt("min_num");
	}

	/**
	 * 开团方式：1 定时开、2 人满开
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	/**
	 * 开团方式：1 定时开、2 人满开
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 一元抢购抽奖活动创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 一元抢购抽奖活动创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 一元抢购抽奖活动修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 一元抢购抽奖活动修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
