package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePointEffective<M extends BasePointEffective<M>> extends BaseModel<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	/**
	 * 用户ID
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 类型（1入账 2出账）
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	/**
	 * 类型（1入账 2出账）
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 业务类型（1注册 2分享转发 3 取消订单 4提现 5消费 6下线首单奖励 7邀请用户注册 8购买商品赠送 9提现审核拒绝退回 10线下录入）
	 */
	public void setBusinessType(java.lang.Integer businessType) {
		set("business_type", businessType);
	}

	/**
	 * 业务类型（1注册 2分享转发 3 取消订单 4提现 5消费 6下线首单奖励 7邀请用户注册 8购买商品赠送 9提现审核拒绝退回 10线下录入）
	 */
	public java.lang.Integer getBusinessType() {
		return getInt("business_type");
	}

	/**
	 * 是否可以提现（1可以2不可以）
	 */
	public void setIsWithdraw(java.lang.Integer isWithdraw) {
		set("is_withdraw", isWithdraw);
	}

	/**
	 * 是否可以提现（1可以2不可以）
	 */
	public java.lang.Integer getIsWithdraw() {
		return getInt("is_withdraw");
	}

	/**
	 * 业务类型对应的ID
	 */
	public void setBusinessId(java.lang.Integer businessId) {
		set("business_id", businessId);
	}

	/**
	 * 业务类型对应的ID
	 */
	public java.lang.Integer getBusinessId() {
		return getInt("business_id");
	}

	/**
	 * 业务编号（秒杀没有ID引起的）
	 */
	public void setBusinessCode(java.lang.String businessCode) {
		set("businessCode", businessCode);
	}

	/**
	 * 业务编号（秒杀没有ID引起的）
	 */
	public java.lang.String getBusinessCode() {
		return getStr("businessCode");
	}

	/**
	 * 积分值
	 */
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	/**
	 * 积分值
	 */
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreatedBy(java.lang.String createdBy) {
		set("created_by", createdBy);
	}

	public java.lang.String getCreatedBy() {
		return getStr("created_by");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

}
