package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseServiceWorker<M extends BaseServiceWorker<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 手机
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	/**
	 * 手机
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

}
