package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCouponLadder<M extends BaseCouponLadder<M>> extends BaseModel<M> implements IBean {

	/**
	 * 自增长ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增长ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 优惠券ID
	 */
	public void setActivityId(java.lang.Integer activityId) {
		set("activity_id", activityId);
	}

	/**
	 * 优惠券ID
	 */
	public java.lang.Integer getActivityId() {
		return getInt("activity_id");
	}

	/**
	 * 购买最小价格 (单位：分)
	 */
	public void setMinPrice(java.lang.Integer minPrice) {
		set("minPrice", minPrice);
	}

	/**
	 * 购买最小价格 (单位：分)
	 */
	public java.lang.Integer getMinPrice() {
		return getInt("minPrice");
	}

	/**
	 * 购买最大价格 (单位：分)
	 */
	public void setMaxPrice(java.lang.Integer maxPrice) {
		set("maxPrice", maxPrice);
	}

	/**
	 * 购买最大价格 (单位：分)
	 */
	public java.lang.Integer getMaxPrice() {
		return getInt("maxPrice");
	}

	/**
	 * 阶梯满减类型-优惠券 面额 (单位：分)
	 */
	public void setOrderPrice(java.lang.Integer orderPrice) {
		set("order_price", orderPrice);
	}

	/**
	 * 阶梯满减类型-优惠券 面额 (单位：分)
	 */
	public java.lang.Integer getOrderPrice() {
		return getInt("order_price");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.lang.Integer createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.lang.Integer getCreateTime() {
		return getInt("create_time");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.lang.Integer updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 修改时间
	 */
	public java.lang.Integer getUpdateTime() {
		return getInt("update_time");
	}

}
