package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLotteryGood<M extends BaseLotteryGood<M>> extends BaseModel<M> implements IBean {

	/**
	 * 自增长id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增长id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 一元抢购抽奖活动ID
	 */
	public void setLotteryId(java.lang.Integer lotteryId) {
		set("lottery_id", lotteryId);
	}

	/**
	 * 一元抢购抽奖活动ID
	 */
	public java.lang.Integer getLotteryId() {
		return getInt("lottery_id");
	}

	/**
	 * 商品ID
	 */
	public void setGoodId(java.lang.Integer goodId) {
		set("good_id", goodId);
	}

	/**
	 * 商品ID
	 */
	public java.lang.Integer getGoodId() {
		return getInt("good_id");
	}

	/**
	 * 规格iD
	 */
	public void setSpecId(java.lang.Integer specId) {
		set("spec_id", specId);
	}

	/**
	 * 规格iD
	 */
	public java.lang.Integer getSpecId() {
		return getInt("spec_id");
	}

	/**
	 * 商品的活动标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	/**
	 * 商品的活动标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 商品图片
	 */
	public void setImgPath(java.lang.String imgPath) {
		set("img_path", imgPath);
	}

	/**
	 * 商品图片
	 */
	public java.lang.String getImgPath() {
		return getStr("img_path");
	}

	/**
	 * 参与活动的商品价格
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	/**
	 * 参与活动的商品价格
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 参与活动的商品数量
	 */
	public void setNum(java.lang.Integer num) {
		set("num", num);
	}

	/**
	 * 参与活动的商品数量
	 */
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	/**
	 * 下单人数
	 */
	public void setOrderNum(java.lang.Integer orderNum) {
		set("orderNum", orderNum);
	}

	/**
	 * 下单人数
	 */
	public java.lang.Integer getOrderNum() {
		return getInt("orderNum");
	}

	/**
	 * 已经被卖掉的数量
	 */
	public void setBuyNum(java.lang.Integer buyNum) {
		set("buy_num", buyNum);
	}

	/**
	 * 已经被卖掉的数量
	 */
	public java.lang.Integer getBuyNum() {
		return getInt("buy_num");
	}

	/**
	 * 活动描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	/**
	 * 活动描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}

	/**
	 * 活动状态：1待审核，2正常，3审核拒绝，4下架商品
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	/**
	 * 活动状态：1待审核，2正常，3审核拒绝，4下架商品
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 排序
	 */
	public void setSortId(java.lang.Integer sortId) {
		set("sort_id", sortId);
	}

	/**
	 * 排序
	 */
	public java.lang.Integer getSortId() {
		return getInt("sort_id");
	}

}
