package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserBalance<M extends BaseUserBalance<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	/**
	 * 用户ID
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 可用金额
	 */
	public void setAvailableAmount(java.math.BigDecimal availableAmount) {
		set("available_amount", availableAmount);
	}

	/**
	 * 可用金额
	 */
	public java.math.BigDecimal getAvailableAmount() {
		return get("available_amount");
	}

	/**
	 * 冻结金额
	 */
	public void setFrozenAmount(java.math.BigDecimal frozenAmount) {
		set("frozen_amount", frozenAmount);
	}

	/**
	 * 冻结金额
	 */
	public java.math.BigDecimal getFrozenAmount() {
		return get("frozen_amount");
	}

	/**
	 * 总金额
	 */
	public void setTotalAmount(java.math.BigDecimal totalAmount) {
		set("total_amount", totalAmount);
	}

	/**
	 * 总金额
	 */
	public java.math.BigDecimal getTotalAmount() {
		return get("total_amount");
	}

	/**
	 * 提现中金额
	 */
	public void setWithdrawalAmount(java.math.BigDecimal withdrawalAmount) {
		set("withdrawal_amount", withdrawalAmount);
	}

	/**
	 * 提现中金额
	 */
	public java.math.BigDecimal getWithdrawalAmount() {
		return get("withdrawal_amount");
	}

	/**
	 * 白金币（与先进1比1的关系，只可消费，不能提现）
	 */
	public void setPlatinumBit(java.math.BigDecimal platinumBit) {
		set("platinum_bit", platinumBit);
	}

	/**
	 * 白金币（与先进1比1的关系，只可消费，不能提现）
	 */
	public java.math.BigDecimal getPlatinumBit() {
		return get("platinum_bit");
	}

	/**
	 * 推广业绩总额(订单销售总额)
	 */
	public void setAchievementAmount(java.math.BigDecimal achievementAmount) {
		set("achievement_amount", achievementAmount);
	}

	/**
	 * 推广业绩总额(订单销售总额)
	 */
	public java.math.BigDecimal getAchievementAmount() {
		return get("achievement_amount");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
