package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSearchWord<M extends BaseSearchWord<M>> extends BaseModel<M> implements IBean {

	/**
	 * 搜索表ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 搜索表ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 搜索关键词，商品关键词
	 */
	public void setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
	}

	/**
	 * 搜索关键词，商品关键词
	 */
	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	/**
	 * 拼音全拼
	 */
	public void setPinyinFull(java.lang.String pinyinFull) {
		set("pinyin_full", pinyinFull);
	}

	/**
	 * 拼音全拼
	 */
	public java.lang.String getPinyinFull() {
		return getStr("pinyin_full");
	}

	/**
	 * 拼音简写
	 */
	public void setPinyinSimple(java.lang.String pinyinSimple) {
		set("pinyin_simple", pinyinSimple);
	}

	/**
	 * 拼音简写
	 */
	public java.lang.String getPinyinSimple() {
		return getStr("pinyin_simple");
	}

	/**
	 * 搜索次数
	 */
	public void setSearchNum(java.lang.Integer searchNum) {
		set("search_num", searchNum);
	}

	/**
	 * 搜索次数
	 */
	public java.lang.Integer getSearchNum() {
		return getInt("search_num");
	}

	/**
	 * 商品数量
	 */
	public void setGoodsNum(java.lang.Integer goodsNum) {
		set("goods_num", goodsNum);
	}

	/**
	 * 商品数量
	 */
	public java.lang.Integer getGoodsNum() {
		return getInt("goods_num");
	}

}
