package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStoreLevelSet<M extends BaseStoreLevelSet<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 等级名称
	 */
	public void setLevelName(java.lang.String levelName) {
		set("level_name", levelName);
	}

	/**
	 * 等级名称
	 */
	public java.lang.String getLevelName() {
		return getStr("level_name");
	}

	/**
	 * 等级
	 */
	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	/**
	 * 等级
	 */
	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
