package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePromOrder<M extends BasePromOrder<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 活动名称
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	/**
	 * 活动名称
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 活动类型 0满额打折,1满额优惠金额,2满额送积分,3满额送优惠券
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	/**
	 * 活动类型 0满额打折,1满额优惠金额,2满额送积分,3满额送优惠券
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 最小金额
	 */
	public void setMoney(java.lang.Float money) {
		set("money", money);
	}

	/**
	 * 最小金额
	 */
	public java.lang.Float getMoney() {
		return getFloat("money");
	}

	/**
	 * 优惠体现
	 */
	public void setExpression(java.lang.String expression) {
		set("expression", expression);
	}

	/**
	 * 优惠体现
	 */
	public java.lang.String getExpression() {
		return getStr("expression");
	}

	/**
	 * 活动描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	/**
	 * 活动描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}

	/**
	 * 活动开始时间
	 */
	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}

	/**
	 * 活动开始时间
	 */
	public java.util.Date getStartTime() {
		return get("start_time");
	}

	/**
	 * 活动结束时间
	 */
	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	/**
	 * 活动结束时间
	 */
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	/**
	 * 1正常，0管理员关闭
	 */
	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}

	/**
	 * 1正常，0管理员关闭
	 */
	public java.lang.Boolean getStatus() {
		return get("status");
	}

	/**
	 * 适用范围
	 */
	public void setGroup(java.lang.String group) {
		set("group", group);
	}

	/**
	 * 适用范围
	 */
	public java.lang.String getGroup() {
		return getStr("group");
	}

	/**
	 * 活动宣传图
	 */
	public void setPromImg(java.lang.String promImg) {
		set("prom_img", promImg);
	}

	/**
	 * 活动宣传图
	 */
	public java.lang.String getPromImg() {
		return getStr("prom_img");
	}

	/**
	 * 商家店铺id
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 商家店铺id
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 排序
	 */
	public void setOrderby(java.lang.Integer orderby) {
		set("orderby", orderby);
	}

	/**
	 * 排序
	 */
	public java.lang.Integer getOrderby() {
		return getInt("orderby");
	}

	/**
	 * 是否推荐
	 */
	public void setRecommend(java.lang.Integer recommend) {
		set("recommend", recommend);
	}

	/**
	 * 是否推荐
	 */
	public java.lang.Integer getRecommend() {
		return getInt("recommend");
	}

	/**
	 * 商品id
	 */
	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}

	/**
	 * 商品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

}
