package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComment<M extends BaseComment<M>> extends BaseModel<M> implements IBean {

	/**
	 * id自增
	 */
	public void setCommentId(java.lang.Integer commentId) {
		set("comment_id", commentId);
	}

	/**
	 * id自增
	 */
	public java.lang.Integer getCommentId() {
		return getInt("comment_id");
	}

	/**
	 * 商品id
	 */
	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}

	/**
	 * 商品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 订单id
	 */
	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}

	/**
	 * 订单id
	 */
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 订单商品id
	 */
	public void setRecId(java.lang.Integer recId) {
		set("rec_id", recId);
	}

	/**
	 * 订单商品id
	 */
	public java.lang.Integer getRecId() {
		return getInt("rec_id");
	}

	/**
	 * 店铺id
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 店铺id
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	/**
	 * 用户id
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	/**
	 * 评论内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}

	/**
	 * 评论内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 评论时间
	 */
	public void setAddTime(java.lang.Long addTime) {
		set("add_time", addTime);
	}

	/**
	 * 评论时间
	 */
	public java.lang.Long getAddTime() {
		return getLong("add_time");
	}

	/**
	 * 评论ip地址
	 */
	public void setIpAddress(java.lang.String ipAddress) {
		set("ip_address", ipAddress);
	}

	/**
	 * 评论ip地址
	 */
	public java.lang.String getIpAddress() {
		return getStr("ip_address");
	}

	/**
	 * 是否显示;0:不显示；1:显示
	 */
	public void setIsShow(java.lang.Long isShow) {
		set("is_show", isShow);
	}

	/**
	 * 是否显示;0:不显示；1:显示
	 */
	public java.lang.Long getIsShow() {
		return getLong("is_show");
	}

	/**
	 * 晒单图片
	 */
	public void setImg(java.lang.String img) {
		set("img", img);
	}

	/**
	 * 晒单图片
	 */
	public java.lang.String getImg() {
		return getStr("img");
	}

	public void setSpecKeyName(java.lang.String specKeyName) {
		set("spec_key_name", specKeyName);
	}

	public java.lang.String getSpecKeyName() {
		return getStr("spec_key_name");
	}

	/**
	 * 商品评价等级，好 中 差
	 */
	public void setGoodsRank(java.math.BigDecimal goodsRank) {
		set("goods_rank", goodsRank);
	}

	/**
	 * 商品评价等级，好 中 差
	 */
	public java.math.BigDecimal getGoodsRank() {
		return get("goods_rank");
	}

	/**
	 * 点赞人数
	 */
	public void setZanNum(java.lang.Integer zanNum) {
		set("zan_num", zanNum);
	}

	/**
	 * 点赞人数
	 */
	public java.lang.Integer getZanNum() {
		return getInt("zan_num");
	}

	public void setZanUserid(java.lang.String zanUserid) {
		set("zan_userid", zanUserid);
	}

	public java.lang.String getZanUserid() {
		return getStr("zan_userid");
	}

	/**
	 * 评论回复数
	 */
	public void setReplyNum(java.lang.Integer replyNum) {
		set("reply_num", replyNum);
	}

	/**
	 * 评论回复数
	 */
	public java.lang.Integer getReplyNum() {
		return getInt("reply_num");
	}

	/**
	 * 是否匿名评价0:是；1不是
	 */
	public void setIsAnonymous(java.lang.Integer isAnonymous) {
		set("is_anonymous", isAnonymous);
	}

	/**
	 * 是否匿名评价0:是；1不是
	 */
	public java.lang.Integer getIsAnonymous() {
		return getInt("is_anonymous");
	}

	/**
	 * 印象标签
	 */
	public void setImpression(java.lang.String impression) {
		set("impression", impression);
	}

	/**
	 * 印象标签
	 */
	public java.lang.String getImpression() {
		return getStr("impression");
	}

	/**
	 * 假删除标识;1:删除,0:未删除
	 */
	public void setDeleted(java.lang.Long deleted) {
		set("deleted", deleted);
	}

	/**
	 * 假删除标识;1:删除,0:未删除
	 */
	public java.lang.Long getDeleted() {
		return getLong("deleted");
	}

	/**
	 * 上级评论ID
	 */
	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}

	/**
	 * 上级评论ID
	 */
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	/**
	 * 订单号
	 */
	public void setOrderSn(java.lang.String orderSn) {
		set("order_sn", orderSn);
	}

	/**
	 * 订单号
	 */
	public java.lang.String getOrderSn() {
		return getStr("order_sn");
	}

}
