package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeliveryDoc<M extends BaseDeliveryDoc<M>> extends BaseModel<M> implements IBean {

	/**
	 * 发货单ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}

	/**
	 * 发货单ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 订单ID
	 */
	public void setOrderId(java.lang.Long orderId) {
		set("order_id", orderId);
	}

	/**
	 * 订单ID
	 */
	public java.lang.Long getOrderId() {
		return getLong("order_id");
	}

	public void setOrderSn(java.lang.String orderSn) {
		set("order_sn", orderSn);
	}

	public java.lang.String getOrderSn() {
		return getStr("order_sn");
	}

	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	/**
	 * 用户ID
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	/**
	 * 管理员ID
	 */
	public void setAdminId(java.lang.Long adminId) {
		set("admin_id", adminId);
	}

	/**
	 * 管理员ID
	 */
	public java.lang.Long getAdminId() {
		return getLong("admin_id");
	}

	/**
	 * 收货人
	 */
	public void setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
	}

	/**
	 * 收货人
	 */
	public java.lang.String getConsignee() {
		return getStr("consignee");
	}

	/**
	 * 邮编
	 */
	public void setZipcode(java.lang.String zipcode) {
		set("zipcode", zipcode);
	}

	/**
	 * 邮编
	 */
	public java.lang.String getZipcode() {
		return getStr("zipcode");
	}

	/**
	 * 联系手机
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	/**
	 * 联系手机
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * 国ID
	 */
	public void setCountry(java.lang.Long country) {
		set("country", country);
	}

	/**
	 * 国ID
	 */
	public java.lang.Long getCountry() {
		return getLong("country");
	}

	/**
	 * 省ID
	 */
	public void setProvince(java.lang.Long province) {
		set("province", province);
	}

	/**
	 * 省ID
	 */
	public java.lang.Long getProvince() {
		return getLong("province");
	}

	/**
	 * 市ID
	 */
	public void setCity(java.lang.Long city) {
		set("city", city);
	}

	/**
	 * 市ID
	 */
	public java.lang.Long getCity() {
		return getLong("city");
	}

	/**
	 * 区ID
	 */
	public void setDistrict(java.lang.Long district) {
		set("district", district);
	}

	/**
	 * 区ID
	 */
	public java.lang.Long getDistrict() {
		return getLong("district");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 物流code
	 */
	public void setShippingCode(java.lang.String shippingCode) {
		set("shipping_code", shippingCode);
	}

	/**
	 * 物流code
	 */
	public java.lang.String getShippingCode() {
		return getStr("shipping_code");
	}

	/**
	 * 快递名称
	 */
	public void setShippingName(java.lang.String shippingName) {
		set("shipping_name", shippingName);
	}

	/**
	 * 快递名称
	 */
	public java.lang.String getShippingName() {
		return getStr("shipping_name");
	}

	/**
	 * 运费
	 */
	public void setShippingPrice(java.math.BigDecimal shippingPrice) {
		set("shipping_price", shippingPrice);
	}

	/**
	 * 运费
	 */
	public java.math.BigDecimal getShippingPrice() {
		return get("shipping_price");
	}

	/**
	 * 物流单号
	 */
	public void setInvoiceNo(java.lang.String invoiceNo) {
		set("invoice_no", invoiceNo);
	}

	/**
	 * 物流单号
	 */
	public java.lang.String getInvoiceNo() {
		return getStr("invoice_no");
	}

	/**
	 * 座机电话
	 */
	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	/**
	 * 座机电话
	 */
	public java.lang.String getTel() {
		return getStr("tel");
	}

	/**
	 * 管理员添加的备注信息
	 */
	public void setNote(java.lang.String note) {
		set("note", note);
	}

	/**
	 * 管理员添加的备注信息
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

	/**
	 * 友好收货时间
	 */
	public void setBestTime(java.lang.Integer bestTime) {
		set("best_time", bestTime);
	}

	/**
	 * 友好收货时间
	 */
	public java.lang.Integer getBestTime() {
		return getInt("best_time");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.lang.Integer createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.lang.Integer getCreateTime() {
		return getInt("create_time");
	}

	/**
	 * 是否已经删除
	 */
	public void setIsDel(java.lang.Boolean isDel) {
		set("is_del", isDel);
	}

	/**
	 * 是否已经删除
	 */
	public java.lang.Boolean getIsDel() {
		return get("is_del");
	}

	/**
	 * 店铺商家id
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 店铺商家id
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 发货方式0自填快递1在线预约2电子面单3无需物流
	 */
	public void setSendType(java.lang.Boolean sendType) {
		set("send_type", sendType);
	}

	/**
	 * 发货方式0自填快递1在线预约2电子面单3无需物流
	 */
	public java.lang.Boolean getSendType() {
		return get("send_type");
	}

	/**
	 * 店铺发货人
	 */
	public void setStoreAddressConsignee(java.lang.String storeAddressConsignee) {
		set("store_address_consignee", storeAddressConsignee);
	}

	/**
	 * 店铺发货人
	 */
	public java.lang.String getStoreAddressConsignee() {
		return getStr("store_address_consignee");
	}

	/**
	 * 发货人手机
	 */
	public void setStoreAddressMobile(java.lang.String storeAddressMobile) {
		set("store_address_mobile", storeAddressMobile);
	}

	/**
	 * 发货人手机
	 */
	public java.lang.String getStoreAddressMobile() {
		return getStr("store_address_mobile");
	}

	/**
	 * 发货省
	 */
	public void setStoreAddressProvinceId(java.lang.Long storeAddressProvinceId) {
		set("store_address_province_id", storeAddressProvinceId);
	}

	/**
	 * 发货省
	 */
	public java.lang.Long getStoreAddressProvinceId() {
		return getLong("store_address_province_id");
	}

	/**
	 * 发货市
	 */
	public void setStoreAddressCityId(java.lang.Long storeAddressCityId) {
		set("store_address_city_id", storeAddressCityId);
	}

	/**
	 * 发货市
	 */
	public java.lang.Long getStoreAddressCityId() {
		return getLong("store_address_city_id");
	}

	/**
	 * 发货县/区
	 */
	public void setStoreAddressDistrictId(java.lang.Long storeAddressDistrictId) {
		set("store_address_district_id", storeAddressDistrictId);
	}

	/**
	 * 发货县/区
	 */
	public java.lang.Long getStoreAddressDistrictId() {
		return getLong("store_address_district_id");
	}

	/**
	 * 发货地址
	 */
	public void setStoreAddress(java.lang.String storeAddress) {
		set("store_address", storeAddress);
	}

	/**
	 * 发货地址
	 */
	public java.lang.String getStoreAddress() {
		return getStr("store_address");
	}

}
