package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFlashSale<M extends BaseFlashSale<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 秒杀活动ID
	 */
	public void setFlashId(java.lang.Integer flashId) {
		set("flashId", flashId);
	}

	/**
	 * 秒杀活动ID
	 */
	public java.lang.Integer getFlashId() {
		return getInt("flashId");
	}

	/**
	 * 商品ID
	 */
	public void setGoodId(java.lang.Long goodId) {
		set("goodId", goodId);
	}

	/**
	 * 商品ID
	 */
	public java.lang.Long getGoodId() {
		return getLong("goodId");
	}

	/**
	 * 商品SKUID
	 */
	public void setSkuId(java.lang.Integer skuId) {
		set("skuId", skuId);
	}

	/**
	 * 商品SKUID
	 */
	public java.lang.Integer getSkuId() {
		return getInt("skuId");
	}

	/**
	 * 秒杀价格
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	/**
	 * 秒杀价格
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 秒杀商品库存
	 */
	public void setGoodNum(java.lang.Integer goodNum) {
		set("goodNum", goodNum);
	}

	/**
	 * 秒杀商品库存
	 */
	public java.lang.Integer getGoodNum() {
		return getInt("goodNum");
	}

	/**
	 * 每人限购数
	 */
	public void setBuyLimit(java.lang.Integer buyLimit) {
		set("buyLimit", buyLimit);
	}

	/**
	 * 每人限购数
	 */
	public java.lang.Integer getBuyLimit() {
		return getInt("buyLimit");
	}

	/**
	 * 购买人数
	 */
	public void setBuyNum(java.lang.Integer buyNum) {
		set("buyNum", buyNum);
	}

	/**
	 * 购买人数
	 */
	public java.lang.Integer getBuyNum() {
		return getInt("buyNum");
	}

	/**
	 * 下单数量
	 */
	public void setOrderNum(java.lang.Integer orderNum) {
		set("orderNum", orderNum);
	}

	/**
	 * 下单数量
	 */
	public java.lang.Integer getOrderNum() {
		return getInt("orderNum");
	}

	/**
	 * 虚假购买数量
	 */
	public void setFakeBuyNum(java.lang.Integer fakeBuyNum) {
		set("fakeBuyNum", fakeBuyNum);
	}

	/**
	 * 虚假购买数量
	 */
	public java.lang.Integer getFakeBuyNum() {
		return getInt("fakeBuyNum");
	}

	/**
	 * 积分抵扣金额
	 */
	public void setPoint(java.math.BigDecimal point) {
		set("point", point);
	}

	/**
	 * 积分抵扣金额
	 */
	public java.math.BigDecimal getPoint() {
		return get("point");
	}

	/**
	 * 积分限制（个人拥有最少这么多积分才可以购买）
	 */
	public void setPointLimit(java.math.BigDecimal pointLimit) {
		set("pointLimit", pointLimit);
	}

	/**
	 * 积分限制（个人拥有最少这么多积分才可以购买）
	 */
	public java.math.BigDecimal getPointLimit() {
		return get("pointLimit");
	}

	/**
	 * 秒杀图片地址
	 */
	public void setImgPath(java.lang.String imgPath) {
		set("imgPath", imgPath);
	}

	/**
	 * 秒杀图片地址
	 */
	public java.lang.String getImgPath() {
		return getStr("imgPath");
	}

	/**
	 * 1上架2下架
	 */
	public void setOffSaleStatus(java.lang.Integer offSaleStatus) {
		set("offSaleStatus", offSaleStatus);
	}

	/**
	 * 1上架2下架
	 */
	public java.lang.Integer getOffSaleStatus() {
		return getInt("offSaleStatus");
	}

	/**
	 * 1真实2虚假
	 */
	public void setIsFake(java.lang.Integer isFake) {
		set("isFake", isFake);
	}

	/**
	 * 1真实2虚假
	 */
	public java.lang.Integer getIsFake() {
		return getInt("isFake");
	}

	/**
	 * 排序字段
	 */
	public void setSorted(java.lang.Integer sorted) {
		set("sorted", sorted);
	}

	/**
	 * 排序字段
	 */
	public java.lang.Integer getSorted() {
		return getInt("sorted");
	}

}
