package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderComment<M extends BaseOrderComment<M>> extends BaseModel<M> implements IBean {

	/**
	 * 订单评论索引id
	 */
	public void setOrderCommemtId(java.lang.Integer orderCommemtId) {
		set("order_commemt_id", orderCommemtId);
	}

	/**
	 * 订单评论索引id
	 */
	public java.lang.Integer getOrderCommemtId() {
		return getInt("order_commemt_id");
	}

	/**
	 * 订单id
	 */
	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}

	/**
	 * 订单id
	 */
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 店铺id
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 店铺id
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 描述相符分数（0~5）
	 */
	public void setDescribeScore(java.math.BigDecimal describeScore) {
		set("describe_score", describeScore);
	}

	/**
	 * 描述相符分数（0~5）
	 */
	public java.math.BigDecimal getDescribeScore() {
		return get("describe_score");
	}

	/**
	 * 卖家服务分数（0~5）
	 */
	public void setSellerScore(java.math.BigDecimal sellerScore) {
		set("seller_score", sellerScore);
	}

	/**
	 * 卖家服务分数（0~5）
	 */
	public java.math.BigDecimal getSellerScore() {
		return get("seller_score");
	}

	/**
	 * 物流服务分数（0~5）
	 */
	public void setLogisticsScore(java.math.BigDecimal logisticsScore) {
		set("logistics_score", logisticsScore);
	}

	/**
	 * 物流服务分数（0~5）
	 */
	public java.math.BigDecimal getLogisticsScore() {
		return get("logistics_score");
	}

	/**
	 * 评分时间
	 */
	public void setCommemtTime(java.lang.Long commemtTime) {
		set("commemt_time", commemtTime);
	}

	/**
	 * 评分时间
	 */
	public java.lang.Long getCommemtTime() {
		return getLong("commemt_time");
	}

	/**
	 * 不删除0；删除：1
	 */
	public void setDeleted(java.lang.Long deleted) {
		set("deleted", deleted);
	}

	/**
	 * 不删除0；删除：1
	 */
	public java.lang.Long getDeleted() {
		return getLong("deleted");
	}

}
