package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCouponList<M extends BaseCouponList<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 优惠券ID
	 */
	public void setCouponId(java.lang.Integer couponId) {
		set("coupon_id", couponId);
	}

	/**
	 * 优惠券ID
	 */
	public java.lang.Integer getCouponId() {
		return getInt("coupon_id");
	}

	/**
	 * 优惠券 对应coupon表id (作废)
	 */
	public void setCid(java.lang.Integer cid) {
		set("cid", cid);
	}

	/**
	 * 优惠券 对应coupon表id (作废)
	 */
	public java.lang.Integer getCid() {
		return getInt("cid");
	}

	/**
	 * 发放类型 0下单赠送 1 按用户发放 2 免费领取 3 线下发放 (作废)
	 */
	public void setType(java.lang.Boolean type) {
		set("type", type);
	}

	/**
	 * 发放类型 0下单赠送 1 按用户发放 2 免费领取 3 线下发放 (作废)
	 */
	public java.lang.Boolean getType() {
		return get("type");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}

	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 订单id
	 */
	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}

	/**
	 * 订单id
	 */
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 状态 1已领取未使用、2已使用、3已过期、4已退回、5已作废
	 */
	public void setCouponStatus(java.lang.Integer couponStatus) {
		set("coupon_status", couponStatus);
	}

	/**
	 * 状态 1已领取未使用、2已使用、3已过期、4已退回、5已作废
	 */
	public java.lang.Integer getCouponStatus() {
		return getInt("coupon_status");
	}

	/**
	 * 送券订单ID (作废)
	 */
	public void setGetOrderId(java.lang.Integer getOrderId) {
		set("get_order_id", getOrderId);
	}

	/**
	 * 送券订单ID (作废)
	 */
	public java.lang.Integer getGetOrderId() {
		return getInt("get_order_id");
	}

	/**
	 * 使用时间 (作废)
	 */
	public void setUseTime(java.lang.Integer useTime) {
		set("use_time", useTime);
	}

	/**
	 * 使用时间 (作废)
	 */
	public java.lang.Integer getUseTime() {
		return getInt("use_time");
	}

	/**
	 * 优惠券兑换码
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}

	/**
	 * 优惠券兑换码
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 发放时间 (作废)
	 */
	public void setSendTime(java.lang.Integer sendTime) {
		set("send_time", sendTime);
	}

	/**
	 * 发放时间 (作废)
	 */
	public java.lang.Integer getSendTime() {
		return getInt("send_time");
	}

	/**
	 * 商家店铺ID (作废)
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 商家店铺ID (作废)
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 0未使用1已使用2已过期 (作废)
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	/**
	 * 0未使用1已使用2已过期 (作废)
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 删除标识;1:删除,0未删除 (作废)
	 */
	public void setDeleted(java.lang.Boolean deleted) {
		set("deleted", deleted);
	}

	/**
	 * 删除标识;1:删除,0未删除 (作废)
	 */
	public java.lang.Boolean getDeleted() {
		return get("deleted");
	}

	/**
	 * 领取时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 领取时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
