package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCoupon<M extends BaseCoupon<M>> extends BaseModel<M> implements IBean {

	/**
	 * 表id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 表id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 优惠券活动规则ID
	 */
	public void setActivityId(java.lang.Integer activityId) {
		set("activity_id", activityId);
	}

	/**
	 * 优惠券活动规则ID
	 */
	public java.lang.Integer getActivityId() {
		return getInt("activity_id");
	}

	/**
	 * 优惠券名字
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 优惠券名字
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 面值/优惠券金 (单位：分) 使用条件为：阶梯满减的券，该字段值为0
	 */
	public void setOrderPrice(java.lang.Integer orderPrice) {
		set("order_price", orderPrice);
	}

	/**
	 * 面值/优惠券金 (单位：分) 使用条件为：阶梯满减的券，该字段值为0
	 */
	public java.lang.Integer getOrderPrice() {
		return getInt("order_price");
	}

	/**
	 * 券的售卖价格 (单位：分)
	 */
	public void setSalePrice(java.lang.Integer salePrice) {
		set("sale_price", salePrice);
	}

	/**
	 * 券的售卖价格 (单位：分)
	 */
	public java.lang.Integer getSalePrice() {
		return getInt("sale_price");
	}

	/**
	 * 优惠券的图片地址
	 */
	public void setImg(java.lang.String img) {
		set("img", img);
	}

	/**
	 * 优惠券的图片地址
	 */
	public java.lang.String getImg() {
		return getStr("img");
	}

	/**
	 * 发放数量
	 */
	public void setNum(java.lang.Integer num) {
		set("num", num);
	}

	/**
	 * 发放数量
	 */
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	/**
	 * 发行人(发放主体) 1：平台发放(成本全部由平台承担)、2：平台发放(成本由平台与店铺共同承担)、3：店铺发放(成本全部由店铺承担)
	 */
	public void setIssuer(java.lang.Integer issuer) {
		set("issuer", issuer);
	}

	/**
	 * 发行人(发放主体) 1：平台发放(成本全部由平台承担)、2：平台发放(成本由平台与店铺共同承担)、3：店铺发放(成本全部由店铺承担)
	 */
	public java.lang.Integer getIssuer() {
		return getInt("issuer");
	}

	/**
	 * 是否公开显示 1：公开显示、2：不公开显示
	 */
	public void setIsShow(java.lang.Integer isShow) {
		set("is_show", isShow);
	}

	/**
	 * 是否公开显示 1：公开显示、2：不公开显示
	 */
	public java.lang.Integer getIsShow() {
		return getInt("is_show");
	}

	/**
	 * 发放类型 0下单赠送 1 按用户发放 2 免费领取 3 线下发放 (作废)
	 */
	public void setType(java.lang.Boolean type) {
		set("type", type);
	}

	/**
	 * 发放类型 0下单赠送 1 按用户发放 2 免费领取 3 线下发放 (作废)
	 */
	public java.lang.Boolean getType() {
		return get("type");
	}

	/**
	 * 使用范围：0全店通用1指定商品可用2指定分类商品可用 (作废)
	 */
	public void setUseType(java.lang.Boolean useType) {
		set("use_type", useType);
	}

	/**
	 * 使用范围：0全店通用1指定商品可用2指定分类商品可用 (作废)
	 */
	public java.lang.Boolean getUseType() {
		return get("use_type");
	}

	/**
	 * 优惠券金额 (作废)
	 */
	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}

	/**
	 * 优惠券金额 (作废)
	 */
	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	/**
	 * 使用条件 (作废)
	 */
	public void setCondition(java.math.BigDecimal condition) {
		set("condition", condition);
	}

	/**
	 * 使用条件 (作废)
	 */
	public java.math.BigDecimal getCondition() {
		return get("condition");
	}

	/**
	 * 发放数量 (作废)
	 */
	public void setCreatenum(java.lang.Integer createnum) {
		set("createnum", createnum);
	}

	/**
	 * 发放数量 (作废)
	 */
	public java.lang.Integer getCreatenum() {
		return getInt("createnum");
	}

	/**
	 * 已领取数量 (作废)
	 */
	public void setSendNum(java.lang.Integer sendNum) {
		set("send_num", sendNum);
	}

	/**
	 * 已领取数量 (作废)
	 */
	public java.lang.Integer getSendNum() {
		return getInt("send_num");
	}

	/**
	 * 已使用数量 (作废)
	 */
	public void setUseNum(java.lang.Integer useNum) {
		set("use_num", useNum);
	}

	/**
	 * 已使用数量 (作废)
	 */
	public java.lang.Integer getUseNum() {
		return getInt("use_num");
	}

	/**
	 * 发放开始时间 (作废) 
	 */
	public void setSendStartTime(java.lang.Integer sendStartTime) {
		set("send_start_time", sendStartTime);
	}

	/**
	 * 发放开始时间 (作废) 
	 */
	public java.lang.Integer getSendStartTime() {
		return getInt("send_start_time");
	}

	/**
	 * 发放结束时间 (作废)
	 */
	public void setSendEndTime(java.lang.Integer sendEndTime) {
		set("send_end_time", sendEndTime);
	}

	/**
	 * 发放结束时间 (作废)
	 */
	public java.lang.Integer getSendEndTime() {
		return getInt("send_end_time");
	}

	/**
	 * 使用开始时间 (作废) 
	 */
	public void setUseStartTime(java.lang.Integer useStartTime) {
		set("use_start_time", useStartTime);
	}

	/**
	 * 使用开始时间 (作废) 
	 */
	public java.lang.Integer getUseStartTime() {
		return getInt("use_start_time");
	}

	/**
	 * 使用结束时间 (作废)
	 */
	public void setUseEndTime(java.lang.Integer useEndTime) {
		set("use_end_time", useEndTime);
	}

	/**
	 * 使用结束时间 (作废)
	 */
	public java.lang.Integer getUseEndTime() {
		return getInt("use_end_time");
	}

	/**
	 * 添加时间 (作废)
	 */
	public void setAddTime(java.lang.Integer addTime) {
		set("add_time", addTime);
	}

	/**
	 * 添加时间 (作废)
	 */
	public java.lang.Integer getAddTime() {
		return getInt("add_time");
	}

	/**
	 * 商家店铺ID
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 商家店铺ID
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	/**
	 * 状态：1有效2无效 (作废)
	 */
	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}

	/**
	 * 状态：1有效2无效 (作废)
	 */
	public java.lang.Boolean getStatus() {
		return get("status");
	}

	/**
	 * 优惠券描述说明
	 */
	public void setCouponInfo(java.lang.String couponInfo) {
		set("coupon_info", couponInfo);
	}

	/**
	 * 优惠券描述说明
	 */
	public java.lang.String getCouponInfo() {
		return getStr("coupon_info");
	}

	/**
	 * 发放开始时间
	 */
	public void setStartSendTime(java.util.Date startSendTime) {
		set("start_send_time", startSendTime);
	}

	/**
	 * 发放开始时间
	 */
	public java.util.Date getStartSendTime() {
		return get("start_send_time");
	}

	/**
	 * 发放结束时间
	 */
	public void setEndSendTime(java.util.Date endSendTime) {
		set("end_send_time", endSendTime);
	}

	/**
	 * 发放结束时间
	 */
	public java.util.Date getEndSendTime() {
		return get("end_send_time");
	}

	/**
	 * 使用有效时间类型(1绝对时间，2相对时间)
	 */
	public void setEffectiveType(java.lang.Integer effectiveType) {
		set("effective_type", effectiveType);
	}

	/**
	 * 使用有效时间类型(1绝对时间，2相对时间)
	 */
	public java.lang.Integer getEffectiveType() {
		return getInt("effective_type");
	}

	/**
	 * 有效时长(单位小时，相对时间的时候有值)
	 */
	public void setEffectiveDuration(java.lang.Integer effectiveDuration) {
		set("effective_duration", effectiveDuration);
	}

	/**
	 * 有效时长(单位小时，相对时间的时候有值)
	 */
	public java.lang.Integer getEffectiveDuration() {
		return getInt("effective_duration");
	}

	/**
	 * 使用开始时间 
	 */
	public void setStartUseTime(java.util.Date startUseTime) {
		set("start_use_time", startUseTime);
	}

	/**
	 * 使用开始时间 
	 */
	public java.util.Date getStartUseTime() {
		return get("start_use_time");
	}

	/**
	 * 使用结束时间
	 */
	public void setEndUseTime(java.util.Date endUseTime) {
		set("end_use_time", endUseTime);
	}

	/**
	 * 使用结束时间
	 */
	public java.util.Date getEndUseTime() {
		return get("end_use_time");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
