package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCouponActivity<M extends BaseCouponActivity<M>> extends BaseModel<M> implements IBean {

	/**
	 * 自增长ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增长ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 优惠券活动名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 优惠券活动名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 发放方式 1：按用户发放、2：用户免费领取、3：发放+领取、4：大客户团购 (用钱购买的购物卡，可以多次使用，有对应记录流水的表)、5：购买代金券(有对应的字段记录券的价格)
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	/**
	 * 发放方式 1：按用户发放、2：用户免费领取、3：发放+领取、4：大客户团购 (用钱购买的购物卡，可以多次使用，有对应记录流水的表)、5：购买代金券(有对应的字段记录券的价格)
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 优惠券活动的图片地址
	 */
	public void setRuleImg(java.lang.String ruleImg) {
		set("rule_img", ruleImg);
	}

	/**
	 * 优惠券活动的图片地址
	 */
	public java.lang.String getRuleImg() {
		return getStr("rule_img");
	}

	/**
	 * 优惠券活动说明
	 */
	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}

	/**
	 * 优惠券活动说明
	 */
	public java.lang.String getDetail() {
		return getStr("detail");
	}

	/**
	 * 使用门槛 1：现金券(不限额度)、2：满减券(满多少减多少)、3：折扣券(打x折扣)
	 */
	public void setUseThreshold(java.lang.Integer useThreshold) {
		set("use_threshold", useThreshold);
	}

	/**
	 * 使用门槛 1：现金券(不限额度)、2：满减券(满多少减多少)、3：折扣券(打x折扣)
	 */
	public java.lang.Integer getUseThreshold() {
		return getInt("use_threshold");
	}

	/**
	 * 使用条件  1：无条件使用(不限额直接使用券)、2：固定金额不叠加满减、3：固定金额叠加满减、4：阶梯满减、5：无条件折扣
	 */
	public void setUseCondition(java.lang.Integer useCondition) {
		set("use_condition", useCondition);
	}

	/**
	 * 使用条件  1：无条件使用(不限额直接使用券)、2：固定金额不叠加满减、3：固定金额叠加满减、4：阶梯满减、5：无条件折扣
	 */
	public java.lang.Integer getUseCondition() {
		return getInt("use_condition");
	}

	/**
	 * 限制数量 1：每人仅限一张、2：每人每天限一张
	 */
	public void setNumLimit(java.lang.Integer numLimit) {
		set("num_limit", numLimit);
	}

	/**
	 * 限制数量 1：每人仅限一张、2：每人每天限一张
	 */
	public java.lang.Integer getNumLimit() {
		return getInt("num_limit");
	}

	/**
	 * 是否叠加 1：同种券可以叠加使用、2：同种券不可以叠加使用、3：与其他券可以叠加使用、4：与其他券不可以叠加使用
	 */
	public void setIsConjunction(java.lang.Integer isConjunction) {
		set("is_conjunction", isConjunction);
	}

	/**
	 * 是否叠加 1：同种券可以叠加使用、2：同种券不可以叠加使用、3：与其他券可以叠加使用、4：与其他券不可以叠加使用
	 */
	public java.lang.Integer getIsConjunction() {
		return getInt("is_conjunction");
	}

	/**
	 * 退款是否返还优惠券 1：返还、2：不返还
	 */
	public void setIsReturn(java.lang.Integer isReturn) {
		set("is_return", isReturn);
	}

	/**
	 * 退款是否返还优惠券 1：返还、2：不返还
	 */
	public java.lang.Integer getIsReturn() {
		return getInt("is_return");
	}

	/**
	 * 是否公开显示 1：公开显示、2：不公开显示
	 */
	public void setIsShow(java.lang.Integer isShow) {
		set("is_show", isShow);
	}

	/**
	 * 是否公开显示 1：公开显示、2：不公开显示
	 */
	public java.lang.Integer getIsShow() {
		return getInt("is_show");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
