package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStoreLevel<M extends BaseStoreLevel<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 商家等级配置ID
	 */
	public void setStoreLevelCategoryId(java.lang.Integer storeLevelCategoryId) {
		set("store_level_category_id", storeLevelCategoryId);
	}

	/**
	 * 商家等级配置ID
	 */
	public java.lang.Integer getStoreLevelCategoryId() {
		return getInt("store_level_category_id");
	}

	/**
	 * 商家ID
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 商家ID
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
