package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRegion<M extends BaseRegion<M>> extends BaseModel<M> implements IBean {

	/**
	 * 区域ID 
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}

	/**
	 * 区域ID 
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 区域名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 区域名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 区域级别：1 省/直辖市/自治区、2 市、3 区/县、4 镇/街道/乡
	 */
	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	/**
	 * 区域级别：1 省/直辖市/自治区、2 市、3 区/县、4 镇/街道/乡
	 */
	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	/**
	 * 区域的父级ID 
	 */
	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}

	/**
	 * 区域的父级ID 
	 */
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

}
