package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends BaseModel<M> implements IBean {

	/**
	 * 表id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	/**
	 * 表id
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 手机号码
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	/**
	 * 手机号码
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 第三方返回昵称
	 */
	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	/**
	 * 第三方返回昵称
	 */
	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	/**
	 * 邮件
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	/**
	 * 邮件
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}

	/**
	 * 0 保密 1 男 2 女
	 */
	public void setSex(java.lang.Long sex) {
		set("sex", sex);
	}

	/**
	 * 0 保密 1 男 2 女
	 */
	public java.lang.Long getSex() {
		return getLong("sex");
	}

	/**
	 * 生日
	 */
	public void setBirthday(java.lang.Integer birthday) {
		set("birthday", birthday);
	}

	/**
	 * 生日
	 */
	public java.lang.Integer getBirthday() {
		return getInt("birthday");
	}

	/**
	 * 所在省ID
	 */
	public void setProvinceId(java.lang.Integer provinceId) {
		set("province_id", provinceId);
	}

	/**
	 * 所在省ID
	 */
	public java.lang.Integer getProvinceId() {
		return getInt("province_id");
	}

	/**
	 * 所在市ID
	 */
	public void setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
	}

	/**
	 * 所在市ID
	 */
	public java.lang.Integer getCityId() {
		return getInt("city_id");
	}

	/**
	 * 所在区ID
	 */
	public void setDistrictId(java.lang.Integer districtId) {
		set("district_id", districtId);
	}

	/**
	 * 所在区ID
	 */
	public java.lang.Integer getDistrictId() {
		return getInt("district_id");
	}

	/**
	 * 支付密码
	 */
	public void setPaypwd(java.lang.String paypwd) {
		set("paypwd", paypwd);
	}

	/**
	 * 支付密码
	 */
	public java.lang.String getPaypwd() {
		return getStr("paypwd");
	}

	/**
	 * 注册时间
	 */
	public void setRegTime(java.lang.Long regTime) {
		set("reg_time", regTime);
	}

	/**
	 * 注册时间
	 */
	public java.lang.Long getRegTime() {
		return getLong("reg_time");
	}

	/**
	 * 最后登录时间
	 */
	public void setLastLogin(java.lang.Long lastLogin) {
		set("last_login", lastLogin);
	}

	/**
	 * 最后登录时间
	 */
	public java.lang.Long getLastLogin() {
		return getLong("last_login");
	}

	/**
	 * 最后登录ip
	 */
	public void setLastIp(java.lang.String lastIp) {
		set("last_ip", lastIp);
	}

	/**
	 * 最后登录ip
	 */
	public java.lang.String getLastIp() {
		return getStr("last_ip");
	}

	/**
	 * QQ
	 */
	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}

	/**
	 * QQ
	 */
	public java.lang.String getQq() {
		return getStr("qq");
	}

	/**
	 * 是否验证手机
	 */
	public void setMobileValidated(java.lang.Integer mobileValidated) {
		set("mobile_validated", mobileValidated);
	}

	/**
	 * 是否验证手机
	 */
	public java.lang.Integer getMobileValidated() {
		return getInt("mobile_validated");
	}

	/**
	 * 头像
	 */
	public void setHeadPic(java.lang.String headPic) {
		set("head_pic", headPic);
	}

	/**
	 * 头像
	 */
	public java.lang.String getHeadPic() {
		return getStr("head_pic");
	}

	/**
	 * 银行名称
	 */
	public void setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
	}

	/**
	 * 银行名称
	 */
	public java.lang.String getBankName() {
		return getStr("bank_name");
	}

	/**
	 * 银行账号
	 */
	public void setBankCard(java.lang.String bankCard) {
		set("bank_card", bankCard);
	}

	/**
	 * 银行账号
	 */
	public java.lang.String getBankCard() {
		return getStr("bank_card");
	}

	/**
	 * 用户真实姓名
	 */
	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}

	/**
	 * 用户真实姓名
	 */
	public java.lang.String getRealname() {
		return getStr("realname");
	}

	/**
	 * 身份证号
	 */
	public void setIdcard(java.lang.String idcard) {
		set("idcard", idcard);
	}

	/**
	 * 身份证号
	 */
	public java.lang.String getIdcard() {
		return getStr("idcard");
	}

	/**
	 * 是否验证电子邮箱
	 */
	public void setEmailValidated(java.lang.Boolean emailValidated) {
		set("email_validated", emailValidated);
	}

	/**
	 * 是否验证电子邮箱
	 */
	public java.lang.Boolean getEmailValidated() {
		return get("email_validated");
	}

	/**
	 * 是否被锁定冻结
	 */
	public void setIsLock(java.lang.Boolean isLock) {
		set("is_lock", isLock);
	}

	/**
	 * 是否被锁定冻结
	 */
	public java.lang.Boolean getIsLock() {
		return get("is_lock");
	}

	/**
	 * 第一个上级
	 */
	public void setFirstLeader(java.lang.Integer firstLeader) {
		set("first_leader", firstLeader);
	}

	/**
	 * 第一个上级
	 */
	public java.lang.Integer getFirstLeader() {
		return getInt("first_leader");
	}

	/**
	 * 微信openID
	 */
	public void setOpenId(java.lang.String openId) {
		set("open_id", openId);
	}

	/**
	 * 微信openID
	 */
	public java.lang.String getOpenId() {
		return getStr("open_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreatedBy(java.lang.String createdBy) {
		set("created_by", createdBy);
	}

	public java.lang.String getCreatedBy() {
		return getStr("created_by");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

	public void setLevelId(java.lang.Integer levelId) {
		set("level_id", levelId);
	}

	public java.lang.Integer getLevelId() {
		return getInt("level_id");
	}

}
