package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShipping<M extends BaseShipping<M>> extends BaseModel<M> implements IBean {

	/**
	 * 物流公司id
	 */
	public void setShippingId(java.lang.Long shippingId) {
		set("shipping_id", shippingId);
	}

	/**
	 * 物流公司id
	 */
	public java.lang.Long getShippingId() {
		return getLong("shipping_id");
	}

	/**
	 * 物流公司名称
	 */
	public void setShippingName(java.lang.String shippingName) {
		set("shipping_name", shippingName);
	}

	/**
	 * 物流公司名称
	 */
	public java.lang.String getShippingName() {
		return getStr("shipping_name");
	}

	/**
	 * 物流公司编码
	 */
	public void setShippingCode(java.lang.String shippingCode) {
		set("shipping_code", shippingCode);
	}

	/**
	 * 物流公司编码
	 */
	public java.lang.String getShippingCode() {
		return getStr("shipping_code");
	}

	/**
	 * 物流描述
	 */
	public void setShippingDesc(java.lang.String shippingDesc) {
		set("shipping_desc", shippingDesc);
	}

	/**
	 * 物流描述
	 */
	public java.lang.String getShippingDesc() {
		return getStr("shipping_desc");
	}

	/**
	 * 物流公司logo
	 */
	public void setShippingLogo(java.lang.String shippingLogo) {
		set("shipping_logo", shippingLogo);
	}

	/**
	 * 物流公司logo
	 */
	public java.lang.String getShippingLogo() {
		return getStr("shipping_logo");
	}

	/**
	 * 运单模板宽度
	 */
	public void setTemplateWidth(java.lang.Long templateWidth) {
		set("template_width", templateWidth);
	}

	/**
	 * 运单模板宽度
	 */
	public java.lang.Long getTemplateWidth() {
		return getLong("template_width");
	}

	/**
	 * 运单模板高度
	 */
	public void setTemplateHeight(java.lang.Long templateHeight) {
		set("template_height", templateHeight);
	}

	/**
	 * 运单模板高度
	 */
	public java.lang.Long getTemplateHeight() {
		return getLong("template_height");
	}

	/**
	 * 运单模板左偏移量
	 */
	public void setTemplateOffsetX(java.lang.Long templateOffsetX) {
		set("template_offset_x", templateOffsetX);
	}

	/**
	 * 运单模板左偏移量
	 */
	public java.lang.Long getTemplateOffsetX() {
		return getLong("template_offset_x");
	}

	/**
	 * 运单模板上偏移量
	 */
	public void setTemplateOffsetY(java.lang.Long templateOffsetY) {
		set("template_offset_y", templateOffsetY);
	}

	/**
	 * 运单模板上偏移量
	 */
	public java.lang.Long getTemplateOffsetY() {
		return getLong("template_offset_y");
	}

	/**
	 * 运单模板图片
	 */
	public void setTemplateImg(java.lang.String templateImg) {
		set("template_img", templateImg);
	}

	/**
	 * 运单模板图片
	 */
	public java.lang.String getTemplateImg() {
		return getStr("template_img");
	}

	/**
	 * 打印项偏移校正
	 */
	public void setTemplateHtml(java.lang.String templateHtml) {
		set("template_html", templateHtml);
	}

	/**
	 * 打印项偏移校正
	 */
	public java.lang.String getTemplateHtml() {
		return getStr("template_html");
	}

}
