package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecharge<M extends BaseRecharge<M>> extends BaseModel<M> implements IBean {

	public void setOrderId(java.lang.Long orderId) {
		set("order_id", orderId);
	}

	public java.lang.Long getOrderId() {
		return getLong("order_id");
	}

	/**
	 * 会员ID
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	/**
	 * 会员ID
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	/**
	 * 会员昵称
	 */
	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	/**
	 * 会员昵称
	 */
	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	/**
	 * 充值单号
	 */
	public void setOrderSn(java.lang.String orderSn) {
		set("order_sn", orderSn);
	}

	/**
	 * 充值单号
	 */
	public java.lang.String getOrderSn() {
		return getStr("order_sn");
	}

	/**
	 * 充值金额
	 */
	public void setAccount(java.math.BigDecimal account) {
		set("account", account);
	}

	/**
	 * 充值金额
	 */
	public java.math.BigDecimal getAccount() {
		return get("account");
	}

	/**
	 * 充值时间
	 */
	public void setCtime(java.lang.Integer ctime) {
		set("ctime", ctime);
	}

	/**
	 * 充值时间
	 */
	public java.lang.Integer getCtime() {
		return getInt("ctime");
	}

	/**
	 * 支付时间
	 */
	public void setPayTime(java.lang.Integer payTime) {
		set("pay_time", payTime);
	}

	/**
	 * 支付时间
	 */
	public java.lang.Integer getPayTime() {
		return getInt("pay_time");
	}

	public void setPayCode(java.lang.String payCode) {
		set("pay_code", payCode);
	}

	public java.lang.String getPayCode() {
		return getStr("pay_code");
	}

	/**
	 * 支付方式
	 */
	public void setPayName(java.lang.String payName) {
		set("pay_name", payName);
	}

	/**
	 * 支付方式
	 */
	public java.lang.String getPayName() {
		return getStr("pay_name");
	}

	/**
	 * 充值状态0:待支付 1:充值成功 2:交易关闭
	 */
	public void setPayStatus(java.lang.Integer payStatus) {
		set("pay_status", payStatus);
	}

	/**
	 * 充值状态0:待支付 1:充值成功 2:交易关闭
	 */
	public java.lang.Integer getPayStatus() {
		return getInt("pay_status");
	}

	/**
	 * 第三方平台交易流水号
	 */
	public void setTransactionId(java.lang.String transactionId) {
		set("transaction_id", transactionId);
	}

	/**
	 * 第三方平台交易流水号
	 */
	public java.lang.String getTransactionId() {
		return getStr("transaction_id");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
