package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFlashInfo<M extends BaseFlashInfo<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 秒杀活动名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 秒杀活动名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 秒杀开始时间
	 */
	public void setBeginTime(java.util.Date beginTime) {
		set("beginTime", beginTime);
	}

	/**
	 * 秒杀开始时间
	 */
	public java.util.Date getBeginTime() {
		return get("beginTime");
	}

	/**
	 * 秒杀结束时间
	 */
	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}

	/**
	 * 秒杀结束时间
	 */
	public java.util.Date getEndTime() {
		return get("endTime");
	}

	/**
	 * 一个人在一个活动中的购买限制数量，0没有限制
	 */
	public void setBuyLimit(java.lang.Integer buyLimit) {
		set("buyLimit", buyLimit);
	}

	/**
	 * 一个人在一个活动中的购买限制数量，0没有限制
	 */
	public java.lang.Integer getBuyLimit() {
		return getInt("buyLimit");
	}

}
