package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfig<M extends BaseConfig<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 字典健
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 字典健
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 字典值
	 */
	public void setValue(java.lang.String value) {
		set("value", value);
	}

	/**
	 * 字典值
	 */
	public java.lang.String getValue() {
		return getStr("value");
	}

	/**
	 * 字典类型（basic为k-v字典）
	 */
	public void setIncType(java.lang.String incType) {
		set("inc_type", incType);
	}

	/**
	 * 字典类型（basic为k-v字典）
	 */
	public java.lang.String getIncType() {
		return getStr("inc_type");
	}

	/**
	 * 字典描述
	 */
	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

	/**
	 * 字典描述
	 */
	public java.lang.String getDesc() {
		return getStr("desc");
	}

}
