package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLotteryOrder<M extends BaseLotteryOrder<M>> extends BaseModel<M> implements IBean {

	/**
	 * 自增长id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增长id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 一元抢购抽奖活动商品ID
	 */
	public void setLotteryGoodId(java.lang.Integer lotteryGoodId) {
		set("lottery_good_id", lotteryGoodId);
	}

	/**
	 * 一元抢购抽奖活动商品ID
	 */
	public java.lang.Integer getLotteryGoodId() {
		return getInt("lottery_good_id");
	}

	/**
	 * 活动场数
	 */
	public void setActivityNum(java.lang.Integer activityNum) {
		set("activity_num", activityNum);
	}

	/**
	 * 活动场数
	 */
	public java.lang.Integer getActivityNum() {
		return getInt("activity_num");
	}

	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	/**
	 * 用户ID
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 一元抢购抽奖活动 订单ID
	 */
	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}

	/**
	 * 一元抢购抽奖活动 订单ID
	 */
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 是否中奖: 1 中奖、2 没中
	 */
	public void setIsWin(java.lang.Integer isWin) {
		set("is_win", isWin);
	}

	/**
	 * 是否中奖: 1 中奖、2 没中
	 */
	public java.lang.Integer getIsWin() {
		return getInt("is_win");
	}

	/**
	 * 开奖时间(人满开/定时开都用这个字段)
	 */
	public void setOpenTime(java.util.Date openTime) {
		set("open_time", openTime);
	}

	/**
	 * 开奖时间(人满开/定时开都用这个字段)
	 */
	public java.util.Date getOpenTime() {
		return get("open_time");
	}

}
