package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBrand<M extends BaseBrand<M>> extends BaseModel<M> implements IBean {

	/**
	 * 品牌表
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}

	/**
	 * 品牌表
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 品牌名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 品牌名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 品牌logo
	 */
	public void setLogo(java.lang.String logo) {
		set("logo", logo);
	}

	/**
	 * 品牌logo
	 */
	public java.lang.String getLogo() {
		return getStr("logo");
	}

	/**
	 * 品牌描述
	 */
	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

	/**
	 * 品牌描述
	 */
	public java.lang.String getDesc() {
		return getStr("desc");
	}

	/**
	 * 品牌地址（字段作废）
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	/**
	 * 品牌地址（字段作废）
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 分类ID
	 */
	public void setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
	}

	/**
	 * 分类ID
	 */
	public java.lang.Integer getCategoryId() {
		return getInt("category_id");
	}

	/**
	 * 排序
	 */
	public void setSort(java.lang.Long sort) {
		set("sort", sort);
	}

	/**
	 * 排序
	 */
	public java.lang.Long getSort() {
		return getLong("sort");
	}

	/**
	 * 是否推荐（0否 1是）
	 */
	public void setIsHot(java.lang.Integer isHot) {
		set("is_hot", isHot);
	}

	/**
	 * 是否推荐（0否 1是）
	 */
	public java.lang.Integer getIsHot() {
		return getInt("is_hot");
	}

	/**
	 * 0正常 1审核中 2审核失败 审核状态
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	/**
	 * 0正常 1审核中 2审核失败 审核状态
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 品牌分类（字段作废）
	 */
	public void setCatName(java.lang.String catName) {
		set("cat_name", catName);
	}

	/**
	 * 品牌分类（字段作废）
	 */
	public java.lang.String getCatName() {
		return getStr("cat_name");
	}

	/**
	 * 一级分类id（字段作废）
	 */
	public void setCatId1(java.lang.Integer catId1) {
		set("cat_id1", catId1);
	}

	/**
	 * 一级分类id（字段作废）
	 */
	public java.lang.Integer getCatId1() {
		return getInt("cat_id1");
	}

	/**
	 * 二级分类id（字段作废）
	 */
	public void setCatId2(java.lang.Integer catId2) {
		set("cat_id2", catId2);
	}

	/**
	 * 二级分类id（字段作废）
	 */
	public java.lang.Integer getCatId2() {
		return getInt("cat_id2");
	}

	/**
	 * 三级分类id（字段作废）
	 */
	public void setCatId3(java.lang.Integer catId3) {
		set("cat_id3", catId3);
	}

	/**
	 * 三级分类id（字段作废）
	 */
	public java.lang.Integer getCatId3() {
		return getInt("cat_id3");
	}

	/**
	 * 商家ID（字段作废）
	 */
	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	/**
	 * 商家ID（字段作废）
	 */
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

}
