package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDoorServer<M extends BaseDoorServer<M>> extends BaseModel<M> implements IBean {

	/**
	 * 安装任务ID
	 */
	public void setIId(java.lang.Integer iId) {
		set("i_id", iId);
	}

	/**
	 * 安装任务ID
	 */
	public java.lang.Integer getIId() {
		return getInt("i_id");
	}

	/**
	 * 订单ID
	 */
	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}

	/**
	 * 订单ID
	 */
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 产品id
	 */
	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}

	/**
	 * 产品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 安装人员姓名
	 */
	public void setIName(java.lang.String iName) {
		set("i_name", iName);
	}

	/**
	 * 安装人员姓名
	 */
	public java.lang.String getIName() {
		return getStr("i_name");
	}

	/**
	 * 安装人员联系方式
	 */
	public void setIPhone(java.lang.String iPhone) {
		set("i_phone", iPhone);
	}

	/**
	 * 安装人员联系方式
	 */
	public java.lang.String getIPhone() {
		return getStr("i_phone");
	}

	/**
	 * 安装的地址
	 */
	public void setIAddress(java.lang.String iAddress) {
		set("i_address", iAddress);
	}

	/**
	 * 安装的地址
	 */
	public java.lang.String getIAddress() {
		return getStr("i_address");
	}

	/**
	 * 预约时间
	 */
	public void setIStartTime(java.util.Date iStartTime) {
		set("i_start_time", iStartTime);
	}

	/**
	 * 预约时间
	 */
	public java.util.Date getIStartTime() {
		return get("i_start_time");
	}

	/**
	 * 安装结束时间
	 */
	public void setIEndTime(java.util.Date iEndTime) {
		set("i_end_time", iEndTime);
	}

	/**
	 * 安装结束时间
	 */
	public java.util.Date getIEndTime() {
		return get("i_end_time");
	}

	/**
	 * 状态（0：待安装，1：已安装，2：已分派，3已取消）
	 */
	public void setIActive(java.lang.Integer iActive) {
		set("i_active", iActive);
	}

	/**
	 * 状态（0：待安装，1：已安装，2：已分派，3已取消）
	 */
	public java.lang.Integer getIActive() {
		return getInt("i_active");
	}

	/**
	 * 分配任务人员
	 */
	public void setOperation(java.lang.String operation) {
		set("operation", operation);
	}

	/**
	 * 分配任务人员
	 */
	public java.lang.String getOperation() {
		return getStr("operation");
	}

	/**
	 * 安装备注
	 */
	public void setIRemarks(java.lang.String iRemarks) {
		set("i_remarks", iRemarks);
	}

	/**
	 * 安装备注
	 */
	public java.lang.String getIRemarks() {
		return getStr("i_remarks");
	}

	/**
	 * 对安装人员的评价
	 */
	public void setINameComment(java.lang.String iNameComment) {
		set("i_name_comment", iNameComment);
	}

	/**
	 * 对安装人员的评价
	 */
	public java.lang.String getINameComment() {
		return getStr("i_name_comment");
	}

	/**
	 * 操作时间
	 */
	public void setTime(java.util.Date time) {
		set("time", time);
	}

	/**
	 * 操作时间
	 */
	public java.util.Date getTime() {
		return get("time");
	}

	/**
	 * 上门服务人员ID
	 */
	public void setWorkerId(java.lang.Integer workerId) {
		set("worker_id", workerId);
	}

	/**
	 * 上门服务人员ID
	 */
	public java.lang.Integer getWorkerId() {
		return getInt("worker_id");
	}

	/**
	 * 预约时间
	 */
	public void setAppointTime(java.util.Date appointTime) {
		set("appoint_time", appointTime);
	}

	/**
	 * 预约时间
	 */
	public java.util.Date getAppointTime() {
		return get("appoint_time");
	}

	/**
	 * 完成时间
	 */
	public void setDoneTime(java.util.Date doneTime) {
		set("done_time", doneTime);
	}

	/**
	 * 完成时间
	 */
	public java.util.Date getDoneTime() {
		return get("done_time");
	}

}
