package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStoreLevelCategory<M extends BaseStoreLevelCategory<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 等级
	 */
	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	/**
	 * 等级
	 */
	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	/**
	 * 商品分类ID
	 */
	public void setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
	}

	/**
	 * 商品分类ID
	 */
	public java.lang.Integer getCategoryId() {
		return getInt("category_id");
	}

	/**
	 * 等级交易金额下限
	 */
	public void setFloorAmount(java.math.BigDecimal floorAmount) {
		set("floor_amount", floorAmount);
	}

	/**
	 * 等级交易金额下限
	 */
	public java.math.BigDecimal getFloorAmount() {
		return get("floor_amount");
	}

	/**
	 * 平台抽成比率
	 */
	public void setCommissionRate(java.math.BigDecimal commissionRate) {
		set("commission_rate", commissionRate);
	}

	/**
	 * 平台抽成比率
	 */
	public java.math.BigDecimal getCommissionRate() {
		return get("commission_rate");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
