package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOperate<M extends BaseOperate<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 主模块名称
	 */
	public void setMenu(java.lang.String menu) {
		set("menu", menu);
	}

	/**
	 * 主模块名称
	 */
	public java.lang.String getMenu() {
		return getStr("menu");
	}

	/**
	 * 子模块名称
	 */
	public void setSubMenu(java.lang.String subMenu) {
		set("subMenu", subMenu);
	}

	/**
	 * 子模块名称
	 */
	public java.lang.String getSubMenu() {
		return getStr("subMenu");
	}

	/**
	 * 操作名称
	 */
	public void setOperate(java.lang.String operate) {
		set("operate", operate);
	}

	/**
	 * 操作名称
	 */
	public java.lang.String getOperate() {
		return getStr("operate");
	}

	public void setSortNo(java.lang.String sortNo) {
		set("sortNo", sortNo);
	}

	public java.lang.String getSortNo() {
		return getStr("sortNo");
	}

}
