package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodCategory<M extends BaseGoodCategory<M>> extends BaseModel<M> implements IBean {

	/**
	 * 商品分类id
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}

	/**
	 * 商品分类id
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 商品分类名称（作废）
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 商品分类名称（作废）
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 手机端显示的商品分类名
	 */
	public void setMobileName(java.lang.String mobileName) {
		set("mobile_name", mobileName);
	}

	/**
	 * 手机端显示的商品分类名
	 */
	public java.lang.String getMobileName() {
		return getStr("mobile_name");
	}

	/**
	 * 父id
	 */
	public void setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
	}

	/**
	 * 父id
	 */
	public java.lang.Long getParentId() {
		return getLong("parent_id");
	}

	/**
	 * 家族图谱
	 */
	public void setParentIdPath(java.lang.String parentIdPath) {
		set("parent_id_path", parentIdPath);
	}

	/**
	 * 家族图谱
	 */
	public java.lang.String getParentIdPath() {
		return getStr("parent_id_path");
	}

	/**
	 * 连带父级的分类，用/分割
	 */
	public void setNamePath(java.lang.String namePath) {
		set("name_path", namePath);
	}

	/**
	 * 连带父级的分类，用/分割
	 */
	public java.lang.String getNamePath() {
		return getStr("name_path");
	}

	/**
	 * ICON 路径，分类的ICON图标
	 */
	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}

	/**
	 * ICON 路径，分类的ICON图标
	 */
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	/**
	 * 分类图片，做宣传显示
	 */
	public void setImage(java.lang.String image) {
		set("image", image);
	}

	/**
	 * 分类图片，做宣传显示
	 */
	public java.lang.String getImage() {
		return getStr("image");
	}

	/**
	 * 是否显示(0否 1是)
	 */
	public void setIsShow(java.lang.Long isShow) {
		set("is_show", isShow);
	}

	/**
	 * 是否显示(0否 1是)
	 */
	public java.lang.Long getIsShow() {
		return getLong("is_show");
	}

	/**
	 * 是否推荐为热门分类(0否 1是)
	 */
	public void setIsHot(java.lang.Integer isHot) {
		set("is_hot", isHot);
	}

	/**
	 * 是否推荐为热门分类(0否 1是)
	 */
	public java.lang.Integer getIsHot() {
		return getInt("is_hot");
	}

	/**
	 * 顺序排序
	 */
	public void setSortOrder(java.lang.Long sortOrder) {
		set("sort_order", sortOrder);
	}

	/**
	 * 顺序排序
	 */
	public java.lang.Long getSortOrder() {
		return getLong("sort_order");
	}

}
