package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStaffRole<M extends BaseStaffRole<M>> extends BaseModel<M> implements IBean {

	public void setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
	}

	public java.lang.Integer getRoleId() {
		return getInt("roleId");
	}

	public void setAdminId(java.lang.Integer adminId) {
		set("adminId", adminId);
	}

	public java.lang.Integer getAdminId() {
		return getInt("adminId");
	}

}
