package com.qw.model.base;

import cn.qw.base.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by QW, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFreightTemplate<M extends BaseFreightTemplate<M>> extends BaseModel<M> implements IBean {

	/**
	 * 运费模板ID
	 */
	public void setTemplateId(java.lang.Long templateId) {
		set("template_id", templateId);
	}

	/**
	 * 运费模板ID
	 */
	public java.lang.Long getTemplateId() {
		return getLong("template_id");
	}

	/**
	 * 模板名称
	 */
	public void setTemplateName(java.lang.String templateName) {
		set("template_name", templateName);
	}

	/**
	 * 模板名称
	 */
	public java.lang.String getTemplateName() {
		return getStr("template_name");
	}

	/**
	 * 0 件数；1 商品重量；2 商品体积
	 */
	public void setType(java.lang.Boolean type) {
		set("type", type);
	}

	/**
	 * 0 件数；1 商品重量；2 商品体积
	 */
	public java.lang.Boolean getType() {
		return get("type");
	}

	/**
	 * 是否启用使用默认运费配置,0:不启用，1:启用
	 */
	public void setIsEnableDefault(java.lang.Boolean isEnableDefault) {
		set("is_enable_default", isEnableDefault);
	}

	/**
	 * 是否启用使用默认运费配置,0:不启用，1:启用
	 */
	public java.lang.Boolean getIsEnableDefault() {
		return get("is_enable_default");
	}

	/**
	 * 店铺Id
	 */
	public void setStoreId(java.lang.Long storeId) {
		set("store_id", storeId);
	}

	/**
	 * 店铺Id
	 */
	public java.lang.Long getStoreId() {
		return getLong("store_id");
	}

}
